feat(landing): created a landing page for creating a new board
entur/tavla pull request #1088
Opened 2023-06-20 12:58 UTC by SharmaTarun1111111

Created a landing page with the purpose to create a new board. User is automatically redirected to the boards admin page when the board is created. 

 
![Screenshot 2023-06-20 at 16 17 28](https://github.com/entur/tavla/assets/70951068/14a5740f-ea5f-4e75-b62d-ab665d458a12)

2023-06-21 08:47 UTC, lindtvedtsebastian requested changes

2023-06-21 08:47 UTC, lindtvedtsebastian commented on next-tavla/src/Landing/styles.module.css
> +    margin: 0 auto;
hva er hensikten her?

2023-06-21 13:20 UTC, ydalir requested changes
God start, litt smågreier men snart i mål 🤠

2023-06-21 13:20 UTC, ydalir commented on next-tavla/src/Admin/scenarios/Landing/index.tsx
> +        setLoading(false)
Trenger vi denne?

2023-06-21 13:20 UTC, ydalir commented on next-tavla/src/Admin/scenarios/Landing/index.tsx
> +            </Heading3>
Burde være Heading2 for riktig HTML semantikk

2023-06-21 13:20 UTC, ydalir commented on next-tavla/src/Admin/scenarios/Landing/styles.module.css
> +}
Dette virker litt for komplisert for det det skal oppnå og kan antagelig forenkles.

2023-06-21 13:20 UTC, ydalir commented on next-tavla/src/Admin/scenarios/Landing/index.tsx
> +                width="auto"
`auto` er default-verdi og kan sløyfes

![image](https://github.com/entur/tavla/assets/18345134/b602b5f0-497f-4028-bdf0-4744189bf58e)

2023-06-22 08:48 UTC, ydalir approved these changes

2023-06-22 09:37 UTC, lindtvedtsebastian approved these changes

2023-06-22 09:39 UTC, merged