Search tile field
entur/tavla pull request #1116
Opened 2023-07-10 13:53 UTC by SharmaTarun1111111

feat(addtile): new layout for adding a tile with a header 
![Screenshot 2023-07-10 at 15 53 14](https://github.com/entur/tavla/assets/70951068/59dd7998-947a-4d46-8593-bab892022748)

2023-07-10 13:59 UTC, stianjsu requested changes

2023-07-10 13:59 UTC, stianjsu commented on next-tavla/src/Admin/scenarios/AddTile/components/AddStopPlaceTile.tsx
Brukes denne noe sted?

2023-07-10 13:59 UTC, stianjsu commented on next-tavla/src/Admin/scenarios/AddTile/index.tsx
>                  </Button>
Hva skjer hvis du trykker legg til før man har valgt stoppested?

2023-07-11 07:52 UTC, ydalir commented on next-tavla/src/Admin/scenarios/AddTile/index.tsx
> +                        else setTileValue(undefined)
e.value sin type er `string | undefined`, så vi trenger ikke gjøre en if-sjekk her

2023-07-11 07:52 UTC, ydalir commented on next-tavla/src/Admin/scenarios/AddTile/index.tsx
> +    const [value, setTileValue] = useState<string>()
Ville kalt denne noe mer beskrivende

2023-07-11 11:24 UTC, ydalir approved these changes

2023-07-12 09:41 UTC, merged