feat(edit): adds toggle for selecting all lines
entur/tavla pull request #1134
Opened 2023-07-17 13:39 UTC by asemwilhelmsen

New toggle for selecting all or none lines. 

![Screenshot 2023-07-17 at 15 38 22](https://github.com/entur/tavla/assets/108051660/8bfa211e-f18b-49c2-89a2-11856facb6c9)

2023-07-17 13:56 UTC, stianjsu requested changes

2023-07-17 13:56 UTC, stianjsu commented on next-tavla/src/Admin/scenarios/SelectLines/index.tsx
> +            </Paragraph>
I de andre komponentene har vi brukt SubParagraph uten noen styles og det passet bra. Utforske det?

2023-07-17 13:56 UTC, stianjsu commented on next-tavla/src/Admin/scenarios/Edit/reducer.tsx
> +                },
kanskje spreade til ny var før vi deleter felter på objektet

2023-07-17 13:56 UTC, stianjsu commented on next-tavla/src/Admin/scenarios/SelectLines/styles.module.css
> +    border-color: var(--primary-lines-grid-color);
kan one-lines med css propertien border:

2023-07-17 14:08 UTC, stianjsu requested changes

2023-07-17 14:08 UTC, stianjsu commented on next-tavla/src/Admin/scenarios/SelectLines/index.tsx
>  function SelectLines<T extends TStopPlaceTile | TQuayTile>({
kan bruke typing på lines fra query

2023-07-18 06:01 UTC, lindtvedtsebastian commented on next-tavla/src/Shared/styles/themes/default.css
Er det meningen at vi kun skal oppdatere default theme og ikke de andre?

2023-07-18 06:03 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/Edit/reducer.tsx
> +                },
Hvorfor ønsker du det?

2023-07-18 07:32 UTC, asemwilhelmsen commented on next-tavla/src/Shared/styles/themes/default.css
Tone sier ja

2023-07-18 08:06 UTC, stianjsu approved these changes

2023-07-18 11:46 UTC, lindtvedtsebastian commented on next-tavla/src/Shared/styles/themes/dark.css
> +    --border-color: var(--colors-blues-blue50);
dark og default er foreløpig det samme, så vi trenger ikke legge inn `--border-color` i dark

2023-07-18 11:46 UTC, lindtvedtsebastian approved these changes

2023-07-19 07:47 UTC, merged