feat(board): split long situations
entur/tavla pull request #1145
Opened 2023-07-20 07:38 UTC by vildeopp

Change situation to have a string as prop and not the whole situation and by default now use the summary of the situation in the deviation column and not the description. In the situations component splits the situations that are longer than 85 characters and at the end marge all situations strings into  the same list.  

<img width="430" alt="Screenshot 2023-07-20 at 09 35 12" src="https://github.com/entur/tavla/assets/64434819/a2ac5a47-799e-4fc1-bd38-cd8b6a1272ee">

<img width="451" alt="Screenshot 2023-07-20 at 09 35 06" src="https://github.com/entur/tavla/assets/64434819/83312936-9ee7-4621-a452-8337dc9d190a">

2023-07-20 12:38 UTC, stianjsu commented
ny føring fra produktueier, heller kutte for lange avviksmeldinger

2023-07-21 08:12 UTC, lindtvedtsebastian requested changes

2023-07-21 08:12 UTC, lindtvedtsebastian commented on next-tavla/src/Board/scenarios/Table/components/Situations/index.tsx
> +    const numberOfSituations = situations.length
trenger ikke disse variablene

2023-07-21 08:28 UTC, lindtvedtsebastian approved these changes

2023-07-21 09:39 UTC, merged