chore(landingpage): styling of landing page
entur/tavla pull request #1147
Opened 2023-07-20 09:50 UTC by SharmaTarun1111111

![Screenshot 2023-07-20 at 11 49 37](https://github.com/entur/tavla/assets/70951068/207824ce-6551-4d50-8bdc-68c04ff01431)

2023-07-20 10:25 UTC, stianjsu requested changes

2023-07-20 10:25 UTC, stianjsu commented on next-tavla/src/Shared/components/Header/styles.module.css
Ken redusere min-width, logoen føles veldig stor på admin og landing. I figma er det ish 185px

2023-07-20 10:25 UTC, stianjsu commented on next-tavla/src/Shared/components/Header/styles.module.css
Kan vurdere å lage egen heading-komponent for board, hvis det blir knot med font størrelse og em-units

2023-07-20 10:25 UTC, stianjsu commented on next-tavla/src/Admin/scenarios/Landing/Scenariolanding.png
kan flyttes til en assets-mappe

2023-07-20 10:25 UTC, stianjsu commented on next-tavla/src/Admin/scenarios/Landing/tavla.png
denne også til assets mappe

2023-07-20 10:25 UTC, stianjsu commented on next-tavla/src/Admin/scenarios/Landing/styles.module.css
> +}
Overskrift ligger veldig tett opptil toppen

2023-07-20 10:25 UTC, stianjsu commented on next-tavla/src/Admin/scenarios/Landing/styles.module.css
> +}
Bør ikke være nødvendig å definere både høyde og bredde. Bedre å definere en, og så vil den andre skaleres automatisk

2023-07-20 10:25 UTC, stianjsu commented on next-tavla/src/Shared/styles/pages/landing.module.css
> +    height: 100vh;
Trenger vi flex-box på root? Kan hende siden er større enn 100vh, hvis den trengs å settes bør vi bruke min-height

2023-07-24 08:14 UTC, lindtvedtsebastian requested changes

2023-07-24 08:14 UTC, lindtvedtsebastian commented on next-tavla/pages/index.tsx
> +            <div className={classes.header}>
Er det nødvendig med en wrapper rundt header?

2023-07-24 08:14 UTC, lindtvedtsebastian commented on next-tavla/src/Shared/assets/landingpagePics/Scenariolanding.png
Kan gjøre navnet på denne filen og `landingpagePics` bedre

2023-07-24 08:14 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/Landing/index.tsx
> +                            <ListItem>knutepunkter</ListItem>
stor bokstav?

2023-07-24 08:14 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/Landing/index.tsx
> +                </div>
Trenger man denne div'en?

2023-07-24 08:14 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/Landing/index.tsx
> +                </div>
Trenger man denne div'en?

2023-07-25 05:26 UTC, lindtvedtsebastian approved these changes

2023-07-25 07:43 UTC, stianjsu approved these changes

2023-07-25 07:43 UTC, merged