fix(edit + board): clarify information
entur/tavla pull request #1148
Opened 2023-07-20 13:20 UTC by asemwilhelmsen

Move transport icons next to header: 
![Screenshot 2023-07-20 at 15 19 28](https://github.com/entur/tavla/assets/108051660/d9d09fad-a925-4382-ab63-81978d1d623f)

Remove pink color on late departure: 
![Screenshot 2023-07-20 at 15 20 00](https://github.com/entur/tavla/assets/108051660/fd6db542-c967-421d-a48c-b53a137ba4f6)

Move toast to top: 
![Screenshot 2023-07-20 at 15 20 27](https://github.com/entur/tavla/assets/108051660/82c1b27e-7893-4a9b-ab90-aaad920cb1e1)

2023-07-20 15:02 UTC, ydalir approved these changes

2023-07-21 06:10 UTC, lindtvedtsebastian requested changes

2023-07-21 06:10 UTC, lindtvedtsebastian commented on next-tavla/pages/edit/[id].tsx
> +            <ToastProvider position={'top-right'}>
du trenger ikke `{}`

2023-07-21 06:10 UTC, lindtvedtsebastian commented on next-tavla/src/Shared/styles/themes/default.css
> -    --table-time-deviation-color: var(--colors-validation-lava-contrast);
kan beholde denne

2023-07-21 06:10 UTC, lindtvedtsebastian commented on next-tavla/src/Shared/styles/themes/light.css
> -    --table-time-deviation-color: var(--colors-validation-lava);
kan beholde denne

2023-07-21 06:32 UTC, lindtvedtsebastian approved these changes

2023-07-21 06:33 UTC, merged