fix(edit): rephrase text
entur/tavla pull request #1153
Opened 2023-07-24 10:46 UTC by vildeopp

Rephrased text in tilesoverview
<img width="1039" alt="Screenshot 2023-07-24 at 12 44 49" src="https://github.com/entur/tavla/assets/64434819/b98712bf-b502-4bb4-a545-dabb94f5125f">

and sorted the platforms in platform dropdown
<img width="465" alt="Screenshot 2023-07-24 at 12 46 18" src="https://github.com/entur/tavla/assets/64434819/5a3cfbbd-0cc9-499e-91a9-3563eb9d9448">

2023-07-24 10:53 UTC, lindtvedtsebastian requested changes
kan ta med sorting i PR navnet også

2023-07-24 10:53 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/TileSettings/components/PlatformDropdown/index.tsx
> +    console.log(quays)
console.log :shipit:

2023-07-24 10:53 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/TileSettings/components/QuaySettings.tsx
> +            : ''
syntes dette kan være sin egen variabel

2023-07-24 14:39 UTC, ydalir requested changes

2023-07-24 14:39 UTC, ydalir commented on next-tavla/src/Admin/scenarios/SelectLines/index.tsx
> +    coach: 'Coach',
Hva med ekspressbuss her?

2023-07-24 14:39 UTC, ydalir commented on next-tavla/src/Admin/scenarios/TileSettings/components/PlatformDropdown/index.tsx
> +                const parsedB = parseIntFromNumberOrAscii(b.label)
Hva gjør denne? Ser ut som noe som kanskje kan bli løst med localeCompare

2023-07-24 14:39 UTC, ydalir commented on next-tavla/src/Admin/scenarios/TileSettings/components/PlatformDropdown/index.tsx
> +
Kan getPlatformLabel defineres utenfor PlatformDropdown-komponenten? Så slipper vi å lage den på nytt hver re-render

2023-07-24 14:39 UTC, ydalir commented on next-tavla/src/Admin/scenarios/TileSettings/components/PlatformDropdown/index.tsx
> +            isNotNullOrUndefinedOrEmptyString(publicCode) ? publicCode : '',
Hvorfor trenger vi isNotNullOrUndefinedOrEmptyString på publicCode men ikke description?

2023-07-25 06:24 UTC, lindtvedtsebastian approved these changes

2023-07-25 06:27 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/TileSettings/components/PlatformDropdown/index.tsx
> +    return [publicCode ? publicCode : '', description ?? ''].join(' ')
her kan vi potensielt ende opp med ett mellomrom til slutt

2023-07-25 08:18 UTC, ydalir approved these changes

2023-07-25 08:38 UTC, merged