feat(edit): toggle transport modes
entur/tavla pull request #1170
Opened 2023-08-22 10:52 UTC by oyvindgrutle

# Description

Toggle between different transport modes

<img width="1363" alt="image" src="https://github.com/entur/tavla/assets/32832996/0235439c-21a9-4d57-bdad-6cb1076dd499">

2023-08-22 12:02 UTC, lindtvedtsebastian requested changes

2023-08-22 12:02 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/SelectLines/index.tsx
> +        const allLinesForMode = new Set(
Er det noe spesifikk grunn til å bruke `Set` her?

2023-08-22 12:02 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/SelectLines/index.tsx
> +        const selectedLinesForMode = new Set(
Er det noe spesifikk grunn til å bruke `Set` her?

2023-08-22 12:56 UTC, oyvindgrutle commented on next-tavla/src/Admin/scenarios/SelectLines/index.tsx
> +import '@entur/travel/dist/styles.css'
Noe av CSS-en blir overskrevet hvis jeg importerer i ```imports.css```. Da blir ikke linjene indenter. Vet ikke helt hvordan jeg overstyrer det.

2023-08-23 05:04 UTC, oyvindgrutle commented on next-tavla/src/Admin/scenarios/SelectLines/index.tsx
> +import '@entur/travel/dist/styles.css'
Ordnet nå

2023-08-23 08:40 UTC, lindtvedtsebastian requested changes

2023-08-23 08:40 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/SelectLines/index.tsx
Når man har valgt noen linjer i en transport mode, og deretter skrur på en annen ender man opp i en litt rar state

![image](https://github.com/entur/tavla/assets/46536611/7de75325-7652-4963-822b-961a92c83362)

Jeg tror det kan være lurt å deselecte alle linjer som ikke er inni en valgt transport mode

2023-08-28 08:08 UTC, lindtvedtsebastian requested changes
Ideelt sett burde de fleste av funksjonene som brukes for linje operasjoner wrappes i useCallback, for å unngå å konstant lage nye funksjoner

https://react.dev/reference/react/useCallback

2023-08-28 08:08 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/SelectLines/index.tsx
> +    }
Burde man skrevet om denne litt?

```typescript
const getNotWhitelistedTransportModeLines = (transportModeWhiteList: TTransportMode[]) => uniqLines
            .filter(
                (line) =>
                    !transportModeWhiteList.includes(
                        line.transportMode ?? 'unknown',
                    ) ?? false,
            )
            .map((line) => line.id)
```

2023-08-28 08:08 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/SelectLines/index.tsx
> +
Denne funksjonen er statisk så den kan plasseres utenfor SelectLines scopet

2023-08-28 12:52 UTC, lindtvedtsebastian approved these changes

2023-08-30 11:01 UTC, merged