feat(date): show date last modified
entur/tavla pull request #1198
Opened 2023-09-05 07:30 UTC by oyvindgrutle

# Show the time the table was last modified

<img width="1549" alt="image" src="https://github.com/entur/tavla/assets/32832996/426820b9-b4ce-451a-b7b0-31c078dae64e">

2023-09-05 07:56 UTC, lindtvedtsebastian requested changes

2023-09-07 11:23 UTC, oyvindgrutle commented
## Show last updated, created and last active
<img width="1571" alt="image" src="https://github.com/entur/tavla/assets/32832996/dd4248ee-8115-47e8-bd05-8716898fdc39">

2023-09-08 05:37 UTC, lindtvedtsebastian requested changes

2023-09-08 05:37 UTC, lindtvedtsebastian commented on next-tavla/pages/api/lastActive.ts
Dette endepunktet er litt "for avansert", vi kan godt kalle dette endepunktet for `ping`. Det eneste du trenger å sende med er en board id, ikke hele boardet (Board id er det eneste man trenger å vite for å kunne avgjøre hvilket board som skal få oppdatert "lastActive"). All ekstra informasjon om boardet er irrelevant, vi ønsker kun å oppdatere et tidspunkt

2023-09-08 05:37 UTC, lindtvedtsebastian commented on next-tavla/src/Shared/hooks/useUpdateLastActive.ts
Samme greia som tidligere, her trenger du ikke gjøre så mye "arbeid", bare send en request til `ping` med hvilken boardID det er snakk om, så fikser det endepunktet å hente ut hva tidspunktet er, osv

2023-09-08 05:38 UTC, lindtvedtsebastian commented on next-tavla/src/Shared/types/settings.ts
> +    dates?: dates
Syntes dette feltet kan renames til "meta", og det kan godt inneholde all metainformasjon (title, dates, version)

2023-09-12 04:37 UTC, lindtvedtsebastian requested changes

2023-09-12 04:37 UTC, lindtvedtsebastian commented on next-tavla/src/Shared/hooks/useUpdateLastActive.ts
> +                    Authorization: 'documentId ' + documentId,
Ikke bruk authorization header for dette, bruk heller dynamic paths slik som vi gjør med andre pages: https://nextjs.org/docs/pages/building-your-application/routing/api-routes#dynamic-api-routes

2023-09-12 04:37 UTC, lindtvedtsebastian commented on next-tavla/src/Shared/hooks/useUpdateLastActive.ts
> +                    Authorization: 'documentId ' + documentId,
Det vil altså være et endepunkt `/ping/[id]`

2023-09-12 04:37 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/BoardList/components/Row/index.tsx
> +            </Cell>
Tenker disse feltene kan droppes i "Mine tavler" visningen, de er primært for vårt eget bruk

2023-09-12 10:24 UTC, lindtvedtsebastian requested changes
Bruk unix timestamps istedenfor date strings, mye lettere å jobbe med

2023-09-12 10:24 UTC, lindtvedtsebastian commented on next-tavla/pages/api/ping/[id].ts
> +        await setLastActive(id as string)
Denne kan castes til BoardID (som egentlig er en string, men ser med "riktig" ut)

2023-09-14 08:43 UTC, lindtvedtsebastian requested changes

2023-09-14 08:43 UTC, lindtvedtsebastian commented on next-tavla/firestore-debug.log
.gitignore denne

2023-09-14 08:43 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/BoardList/components/Row/index.tsx
> +    }
Legg denne i en utils fil

2023-09-14 08:43 UTC, lindtvedtsebastian commented on next-tavla/src/Shared/hooks/useUpdateLastActive.ts
> +        const board = (await getBoard(documentId)) || undefined
Dette vil ikke fungere, gjør hele hooken "dummere", send en ping uansett, så kjører vi logikken på server siden

2023-09-14 12:03 UTC, lindtvedtsebastian requested changes

2023-09-14 12:03 UTC, lindtvedtsebastian commented on next-tavla/pages/api/ping/[id].ts
> +    }
Gjør det noe at man prøver å pinge et board som ikke finnes? Du kan gjøre denne hooken enda dummere. Send en ping request hver time (uten å sjekke noen ting her), så håndterer vi all logikken rundt det på server siden

2023-09-14 12:03 UTC, lindtvedtsebastian commented on next-tavla/pages/[id].tsx
> +    useUpdateLastActive(board.id || '')
Det burde ikke gjøre noe at board.id ikke finnes, men hvis det hadde gjort noe skulle du ha brukt ternary operator istedenfor `??`

2023-09-18 12:50 UTC, lindtvedtsebastian requested changes

2023-09-18 12:50 UTC, lindtvedtsebastian commented on next-tavla/.prettierignore
Dette hører til en annen PR som allerede har blitt merget?

2023-09-18 12:50 UTC, lindtvedtsebastian commented on next-tavla/.gitignore
Dette hører til en annen PR som allerede har blitt merget?

2023-09-19 09:43 UTC, lindtvedtsebastian requested changes

2023-09-19 09:43 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/utils/firebase.ts
> +    if (!board.exists) return
Siden du bruker en try catch blokk i `/ping` regner jeg med at du egentlig mener å kaste en exception her istedenfor å returne

2023-09-19 10:53 UTC, lindtvedtsebastian approved these changes

2023-09-19 10:55 UTC, merged