feat(edit title): added automatic focus and text selection when editing title
entur/tavla pull request #1204
Opened 2023-09-06 11:51 UTC by fredrbus

### Description

Makes it so that the textfield is focused on and text selected when you click the "edit title"-button.

2023-09-08 05:28 UTC, lindtvedtsebastian requested changes

2023-09-08 05:28 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/BoardTitle/index.tsx
> +                id="boardTitle-input"
Hva brukes denne id'en til?

2023-09-12 05:14 UTC, lindtvedtsebastian requested changes

2023-09-12 05:14 UTC, lindtvedtsebastian commented on next-tavla/src/Board/scenarios/Table/components/Line/styles.module.css
> +    justify-content: start;
`start` har dårlige støtte, bruk `flex-start` istedenfor

https://caniuse.com/mdn-api_sensor_start

2023-09-12 05:14 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/BoardTitle/index.tsx
Det er ikke mulig å endre navn til noe annet en enkle bokstaver

2023-09-14 12:18 UTC, lindtvedtsebastian requested changes

2023-09-14 12:18 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/BoardTitle/index.tsx
Jeg tror hele denne PR kan byttes ut med denne `ref'en` i TextField:

`ref={(ref) => ref?.select()}`

2023-09-14 12:19 UTC, fredrbus commented on next-tavla/src/Admin/scenarios/BoardTitle/index.tsx
🙃
Tar en titt

2023-09-15 05:02 UTC, lindtvedtsebastian requested changes

2023-09-15 05:02 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/BoardTitle/index.tsx
Bruk en callback for å sette focus

```typescript
const focus = useCallback((ref: HTMLInputElement) => ref?.select(), [])
...
ref={focus}
```

2023-09-19 09:10 UTC, fredrbus commented
--> #1229

2023-09-19 09:10 UTC, closed without merging