feat(delete): delete board from 'Mine tavler'
entur/tavla pull request #1237
Opened 2023-09-22 10:19 UTC by oyvindgrutle

# Delete board from 'Mine tavler'

![image](https://github.com/entur/tavla/assets/32832996/d9815623-e7fc-4706-96c1-3a6de1b5bf82)

2023-09-25 05:52 UTC, lindtvedtsebastian requested changes

2023-09-25 05:52 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/utils/firebase.ts
> +}
Må vel sjekke organisasjon også

2023-09-25 05:52 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/Boards/components/Delete/index.tsx
> +            <Modal
Modalen burde ikke ligge inni IconButton, bruk fragment rundt dem istedenfor

2023-09-25 05:52 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/Boards/components/Delete/index.tsx
> +    const [showModal, setShowModal] = useState(false)
Skulle vi vurdert en hook for denne typen state bruk?

2023-09-25 08:18 UTC, lindtvedtsebastian requested changes

2023-09-25 08:18 UTC, lindtvedtsebastian commented on next-tavla/src/Shared/hooks/useToggle.ts
Bruk denne hooken i <DeleteTile/> også

2023-09-25 08:20 UTC, oyvindgrutle commented on next-tavla/src/Shared/hooks/useToggle.ts
> +    return [isOpen, open, close] as const
Enig!

2023-09-25 08:25 UTC, oyvindgrutle commented on next-tavla/src/Shared/hooks/useToggle.ts
Der skal den vel allerede være brukt?

2023-09-26 05:51 UTC, lindtvedtsebastian requested changes

2023-09-26 05:51 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/Boards/utils/delete.ts
> +export { deleteBoard }
I utils filer er det vanlig å exporte inline framfor på slutten av filen

2023-09-26 05:51 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/utils/firebase.ts
> +}
Legg til samme sjekken på organisasjon som finnes i useCanWriteBoard

2023-09-26 06:54 UTC, lindtvedtsebastian approved these changes

2023-09-26 07:02 UTC, merged