feat(columns): custom columns
entur/tavla pull request #1241
Opened 2023-09-25 14:41 UTC by fredrbus

Remake of #1209, #1215

### Description

Adds support for optional columns in the board list overview.

| URL disabled | URL enabled |
|--------|--------|
| <img width="1109" alt="image" src="https://github.com/entur/tavla/assets/61384979/9c82ce4d-39ce-4d68-a37a-0af65183e5b8"> | <img width="1109" alt="image" src="https://github.com/entur/tavla/assets/61384979/2f3687bd-382d-4de9-9985-50a927763aac"> |

2023-09-28 08:50 UTC, lindtvedtsebastian requested changes

2023-09-28 08:50 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/components/SortableHandle.tsx
du kan reverte hele denne filen, trenger ikke disse endringene såvidt jeg kan se

2023-09-28 08:50 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/Boards/components/Column/Link.tsx
> +    return <SortableColumn column={'url'}>{link}</SortableColumn>
unødvendig {} rundt url

2023-09-28 08:50 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/Boards/components/Column/SortableColumn.tsx
Du kan fjerne className propen, ser ikke ut som den brukes

2023-09-28 08:50 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/Boards/components/Column/index.tsx
> +        lastModified: <LastModified timestamp={board.meta?.dateModified} />,
Vi kan godt beholde denne switchen

2023-09-28 08:50 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/Boards/components/TableHeader/ColumnHeader.tsx
> +        <>
Hva er hensikten med denne fragmenten

2023-09-28 08:50 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/Boards/components/TableHeader/styles.module.css
> +    /* padding-bottom: 0.5em; */
Tror ikke vi trenger denne linjen

2023-09-28 08:50 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/Boards/components/TableHeader/styles.module.css
>      color: var(--colors-brand-lavender);
Er det en variable som vi har definert vi kan bruke her?

2023-09-28 08:50 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/Boards/components/TableRows/index.tsx
> +    const { boards, columns, columnOrder, search } = useBoardsSettings()
brukes columnOrder enda?

2023-09-28 08:50 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/types/boards.ts
> +    columnOrder: TBoardsColumn[]
Brukes denne?

2023-09-28 09:48 UTC, lindtvedtsebastian requested changes

2023-09-28 09:48 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/Boards/components/Column/SortableColumn.tsx
> +    }
Denne koden finnes to steder

2023-09-28 09:48 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/Boards/components/TableHeader/ColumnHeader.tsx
> +    } as CSSProperties
DRY

2023-09-29 05:00 UTC, lindtvedtsebastian requested changes

2023-09-29 05:00 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/Boards/hooks/useSortableAttributes.ts
Denne filen har ikke samme navn som hooken

2023-09-29 05:00 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/Boards/components/Column/SortableColumn.tsx
> +    if (thisColumnActive) style.backgroundColor = 'var(--colors-brand-blue)'
Kunne vi brukt en av våre farger her?

2023-09-29 05:00 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/Boards/components/TableHeader/ColumnHeader.tsx
> +    } as CSSProperties
Du kan godt sette denne stylen på samme måte som linje 15 i `SortableColumn`

2023-09-29 05:00 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/Boards/components/TableHeader/ColumnHeader.tsx
> +            <Tooltip placement={'top'} content={'Dra for å flytte'}>
Unødvendige `{}` rundt placement og content

2023-09-29 05:00 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/Boards/hooks/useSortableAttributes.ts
> +        } as CSSProperties)
Sett style på samme måte som linje 15 i SortableColumn

2023-09-29 05:00 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/Boards/components/ToggleBoardsColumns/index.tsx
> +                        <Heading4 className={classes.heading}>
Er det riktig med Heading4 her?

2023-09-29 05:00 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/Boards/index.tsx
> +            {' '}
Trenger vi denne

2023-09-29 05:00 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/Boards/index.tsx
> +    }
Inline funksjoner gjør vi med arrow functions, her er det vel like greit å bruke en callback også?

2023-10-02 09:40 UTC, lindtvedtsebastian requested changes

2023-10-02 09:40 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/Boards/components/ToggleBoardsColumns/index.tsx
globals.css

2023-10-02 09:48 UTC, oyvindgrutle commented
Kolonnen fortsetter utenfor viewpoort hvis du drar den utenfor skjermen til høyre. Se video.

https://github.com/entur/tavla/assets/32832996/77ee84d5-ce02-457c-a9a0-6035e038e394

2023-10-02 12:46 UTC, lindtvedtsebastian approved these changes

2023-10-02 12:47 UTC, merged