feat(reset-password): reset password
entur/tavla pull request #1243
Opened 2023-09-28 06:03 UTC by oyvindgrutle

# Forgot password functionality

## New page in modal for "Glemt passord"

User will receive an e-mail with a link, that will redirect the user to ```/reset/[oob]``` where the user can set a new password. 

<img width="428" alt="image" src="https://github.com/entur/tavla/assets/32832996/394d3919-efc6-4300-84e6-6928afe5bd6d">
<img width="435" alt="image" src="https://github.com/entur/tavla/assets/32832996/bdc834a6-a5b0-41ba-8dd2-13923b7d4c22">

2023-09-29 05:19 UTC, lindtvedtsebastian requested changes

2023-09-29 05:19 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/Login/components/ResetPassword.tsx
> +    const { error, setError, getTextFieldPropsForType } = useFirebaseAuthError()
Har du dekket de ekstra feilmeldinger som kan oppstå ved bruk av funksjonene `sendPasswordResetEmail` og `confirmPasswordReset` i useFirebaseAuthError hooken?

2023-09-29 05:19 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/Login/components/ResetPassword.tsx
> +            console.log(resetPassword)
console.log()

2023-09-29 05:19 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/Login/components/ResetPassword.tsx
> +        const email = data.email.value
Dette tror jeg du kunne assignet direkte med 
```tsx
const {email} = event.currentTarget as unknown as {
            email: HTMLInputElement
        }
```

2023-09-29 05:19 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/Login/components/ResetPassword.tsx
> +                Vi sender deg en e-post for å lage et nytt passord.
Syntes denne setningen kan omformuleres litt

2023-09-29 05:19 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/ResetPassword/index.tsx
> +            console.log(error)
console.log()

2023-09-29 05:19 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/ResetPassword/index.tsx
> +                </>
Er det en spesiell grunn til at dette er en fragment?

2023-09-29 05:19 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/ResetPassword/index.tsx
> +            data.repeat_password.value = ''
Er det nødvendig å nullstille disse?

2023-09-29 08:27 UTC, oyvindgrutle commented on next-tavla/src/Admin/scenarios/ResetPassword/index.tsx
> +            data.repeat_password.value = ''
Nei, det henger igjen fra før når formet fortsatt ble rendret.

2023-09-29 08:41 UTC, oyvindgrutle commented on next-tavla/src/Admin/scenarios/Login/components/ResetPassword.tsx
> +        const email = data.email.value
Virker ikke sånn.

2023-10-02 06:47 UTC, lindtvedtsebastian approved these changes

2023-10-02 06:47 UTC, merged