chore(delete): delete modal
entur/tavla pull request #1270
Opened 2023-10-11 12:58 UTC by oyvindgrutle

Own modal for deleting a board to avoid duplicate code.

2023-10-11 13:53 UTC, fredrbus requested changes

2023-10-11 13:53 UTC, fredrbus commented on next-tavla/src/Admin/components/DeleteModal/index.tsx
> +        <>
Denne fragmenten har vel ingen funksjon

2023-10-11 13:53 UTC, fredrbus commented on next-tavla/src/Admin/components/DeleteModal/index.tsx
> +    onDelete: () => void
Synes vi heller kan bruke `deleteHandler`, siden `onDelete` ligner veldig på navnekonvensjonen for DOM-event handlers

2023-10-11 13:53 UTC, fredrbus commented on next-tavla/src/Admin/scenarios/Edit/components/DeleteBoard/index.tsx
> +            console.log(error)
Vet ikke om vi skal ha console logs i prod

2023-10-11 13:53 UTC, fredrbus commented on next-tavla/src/Admin/components/DeleteModal/index.tsx
> +                className={classes.deleteModal}
`.deleteModal` består stort sett bare av mange flexbox-props, så denne burde erstattes med klassene vi har i `global.css`, og om noen av propsene ikke finnes burde de legges til

2023-10-11 13:53 UTC, fredrbus commented on next-tavla/src/Admin/components/DeleteModal/index.tsx
> +                <div className={classes.actions}>
Samme som over

2023-10-12 07:36 UTC, lindtvedtsebastian requested changes

2023-10-12 09:24 UTC, lindtvedtsebastian requested changes

2023-10-12 09:24 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/components/DeleteModal/styles.module.css
Brukes denne filen?

2023-10-12 09:24 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/components/DeleteModal/index.tsx
> +            <div className="flexRow justifyAround alignCenter selfStretch">
Kunne vi fjernet selfStretch? Eller er den viktig?

2023-10-12 09:48 UTC, oyvindgrutle commented on next-tavla/src/Admin/components/DeleteModal/index.tsx
> +            <div className="flexRow justifyAround alignCenter selfStretch">
Kan fjerne den.

2023-10-12 10:30 UTC, closed without merging