feat(edit): select authorities
entur/tavla pull request #1271
Opened 2023-10-11 14:40 UTC by natashatikhonova

### Description:
- multiselector for choosing what authorities to show
- showing authorities only for the lines that belong to certain stop place/quay
- filter lines based on the authorities user selected
- set and send whitelisted authorities to query for getting departures information 

NB!: squashed and merged with main due to conflicts and refactoring in tiles settings

### Images: 
![image](https://github.com/entur/tavla/assets/64562118/9fedf63f-144a-433c-89d3-4c5cbc96ccc2)
![image](https://github.com/entur/tavla/assets/64562118/3577abd4-526d-4e1b-8634-bad998bf0a83)
![image](https://github.com/entur/tavla/assets/64562118/1a2f0466-186f-4704-b6e2-0965c9981915)

2023-10-11 17:00 UTC, fredrbus requested changes

2023-10-12 08:44 UTC, lindtvedtsebastian requested changes

2023-10-12 08:44 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/Edit/components/TileSettings/QuaySettings.tsx
> +            </div>
Samme som StopPlaceSettings

2023-10-12 10:39 UTC, natashatikhonova commented on next-tavla/src/Admin/scenarios/Edit/components/SelectAuthorities/utils/useAuthoritiesSearch.ts
> +    const authoritiesList = removeDuplicates(
Man kan ikke hente authorities for stop_place/quay, så de blir hentet via hver linje. (Hver linje har authority parameter). Derfor måtte jeg hente ut slik. Skal prøve å forenkle den litt, men si ifra om du har noen forslag

2023-10-16 08:31 UTC, closed without merging