feat(edit): auto-save functionality
entur/tavla pull request #1274
Opened 2023-10-12 11:12 UTC by lindtvedtsebastian

2023-10-12 12:18 UTC, fredrbus requested changes

2023-10-12 12:18 UTC, fredrbus commented on next-tavla/src/Admin/scenarios/Edit/hooks/useAutoSaveSettings.ts
> +        else setStatus('Du har endringer som ikke er lagret')
Synes det var rart at jeg fikk beskjed om at jeg har ulagrede endringer, når alt jeg har gjort er å slå av autolagring, altså ikke endret noe 🤔

2023-10-12 12:18 UTC, fredrbus commented on next-tavla/src/Admin/scenarios/Edit/components/AutoSave/index.tsx
Synes det var litt irriterende at den flyttet seg når jeg aktiverte og deaktiverte knappen 🥴 

https://github.com/entur/tavla/assets/61384979/e759a3a9-50b1-4deb-93cb-985f0e124d09

2023-10-12 12:18 UTC, fredrbus commented on next-tavla/src/Admin/scenarios/Edit/components/BoardSettings/index.tsx
> +            <AutoSave board={board} />
Settings-containeren har sikkert vært ute av alignment en stund, men det ble veldig tydelig nå

![image](https://github.com/entur/tavla/assets/61384979/1d7eb2c7-2a5f-4d5f-8296-30f3a4b8d30c)

2023-10-12 12:18 UTC, fredrbus commented on next-tavla/src/Admin/scenarios/Edit/components/AutoSave/index.tsx
> +            <Heading5 as={Heading2}>Autolagring</Heading5>
Her kan vi droppe import av `Heading2` og bare skrive `as='h2'`

2023-10-12 12:18 UTC, fredrbus commented on next-tavla/src/Admin/scenarios/Edit/components/BoardTitle/index.tsx
> +            <Heading5 as={Heading2}>Navn på tavla</Heading5>
Samme som i AutoSave, bare bruke `'h2'`

2023-10-12 12:18 UTC, fredrbus commented on next-tavla/src/Admin/scenarios/Edit/components/AutoSave/index.tsx
> +                        <IconButton onClick={saveSettings}>
Synes det var veldig lite intuitivt at dette var en knapp når det kom på høyresiden av en checkbox med tekst, ikonet så mer ut som dekor.

2023-10-12 12:18 UTC, fredrbus commented on next-tavla/src/Admin/scenarios/Edit/components/AutoSave/index.tsx
> +    const toggleAutoSave = () => setAutoSave(!autoSave)
Kanskje legge toggle-funksjonen inn i useToggle?

2023-10-16 07:32 UTC, natashatikhonova approved these changes

2023-10-16 07:37 UTC, merged