Create organization
entur/tavla pull request #1285
Opened 2023-10-20 09:21 UTC by natashatikhonova

### Description: 
- modal for creating new organization 
- user can now set a title for a new organization
- user who created organization is automatically set as owner of organization
- toast is sent out when organization is created
NB!: to see organization you have created - check emulator

### Images: 
![image](https://github.com/entur/tavla/assets/64562118/6a94f494-3235-4e2d-aa8b-c66c4dd9c8e3)
![image](https://github.com/entur/tavla/assets/64562118/f71ba514-f6b3-4dcd-a1f7-670cd1479ba1)
![image](https://github.com/entur/tavla/assets/64562118/d163762b-76df-46a3-b0d9-c116153831d3)

2023-10-20 09:32 UTC, lindtvedtsebastian requested changes

2023-10-20 12:32 UTC, fredrbus approved these changes

2023-10-23 07:35 UTC, lindtvedtsebastian requested changes

2023-10-23 07:35 UTC, lindtvedtsebastian commented on next-tavla/pages/api/organization.ts
> +                return response.status(200).json({ oID: oID })
kan ha det som oid istedenfor oID

2023-10-23 07:35 UTC, lindtvedtsebastian commented on next-tavla/pages/organizations/[id].tsx
> +    console.log(id)
console.log

2023-10-23 07:35 UTC, lindtvedtsebastian commented on next-tavla/pages/organizations/[id].tsx
> +                    <div></div>
Kan legge inn IDen her

2023-10-23 07:35 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/Organizations/components/CreateOrganization.tsx/index.tsx
> +    }
Kan kjøre en toast hvis man feiler på å lage en ny org

2023-10-23 11:33 UTC, lindtvedtsebastian approved these changes

2023-10-23 11:33 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/Organizations/components/CreateOrganization.tsx/index.tsx
> +    }
Foreslår at vi returnerer tidlig hvis det ikke er 200 

```ts
    const saveOrganization = async () => {
        const req = await createOrganizationRequest(organizationName)

        if (req.status !== 200)
            return addToast({
                title: 'Noe gikk galt',
                content: 'Kunne ikke opprette organisajon',
                variant: 'info',
            })

        const organization = await req.json()
        router.push(`/organizations/${organization.oid}`)
    }
```

2023-10-23 15:02 UTC, merged