feat(organizations): organizations list
entur/tavla pull request #1290
Opened 2023-10-24 13:29 UTC by fredrbus

### Description

Added a list/table of organizations that the user is a part of, as well as their role in it and actions they can perform.

### Result

| User in organizations | User with no organizations |
|--------|--------|
| ![image](https://github.com/entur/tavla/assets/61384979/bc48ca4f-b131-4683-bb54-26a977361306) | ![image](https://github.com/entur/tavla/assets/61384979/16b0c9e3-9270-4ae1-97c2-f9ced01048d7) |

2023-10-24 13:34 UTC, fredrbus commented on next-tavla/pages/organizations/index.tsx
> +                        value={{ userId, organizations }}
Litt usikker på hele strukturen på siden og contexten, men må jo på en eller annen måte ha med seg `userId` for å finne relasjonen mellom brukeren og organisasjonen.

Kom gjerne med andre forslag 🤠

2023-10-26 05:40 UTC, lindtvedtsebastian requested changes

2023-10-26 05:40 UTC, lindtvedtsebastian commented on next-tavla/pages/organizations/[id].tsx
> +            <AdminHeader loggedIn={true} />
Du kan droppe å sende inn en verdi i loggedIn

```tsx
<AdminHeader loggedIn/>
```

2023-10-26 05:40 UTC, lindtvedtsebastian commented on next-tavla/pages/organizations/index.tsx
> +            <AdminHeader loggedIn={true} />
Samme som tidligere

2023-10-26 05:40 UTC, lindtvedtsebastian commented on next-tavla/pages/organizations/index.tsx
> +                    <Organizations {...{ userId, organizations }} />
Om man ikke ønsker å bruke disse propsene separat trenger man ikke destrukturere dem i utgangspunktet

```tsx
function OrganizationsPage(props: {
    organizations: TOrganization[]
    userId: TUserID
}) {
    return (
        <div className={classes.root}>
            <AdminHeader loggedIn={true} />
            <Contrast>
                <ToastProvider>
                    <Organizations {...props} />
                </ToastProvider>
            </Contrast>
        </div>
    )
}
```

2023-10-26 05:40 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/Organizations/index.tsx
> +                        className="grid w-30"
Vi burde bruke 100% av bredden, ser litt rart ut nå

2023-10-26 05:40 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/Organizations/components/TableHeader/styles.module.css
> +    border-bottom: var(--colors-blues-blue20) solid;
Syntes vi burde bruke en av våre farger her

2023-10-26 05:40 UTC, lindtvedtsebastian commented on next-tavla/src/Shared/styles/spacing.css
> +}
Vet ikke helt om jeg ser verdien av dette. Vi burde jo sjeldent måtte behøve å sette høyde og bredde på denne måten, det er lite responsivt og skalerer dårlig. La oss heller se om vi finner en bedre måte å løse det underliggende problemet som har ført til at vi må sette disse verdiene

2023-10-26 08:36 UTC, lindtvedtsebastian approved these changes

2023-10-26 11:37 UTC, oyvindgrutle approved these changes

2023-10-26 12:17 UTC, merged