feat(boards): show boards for each organization
entur/tavla pull request #1294
Opened 2023-10-30 14:01 UTC by natashatikhonova

### Description:
- dropdown where you can choose boards for which organization will be shown 
- new route for private boards: /boards
- new route for each organizations boards: /boards/$oID

### Images:
![Screenshot 2023-10-30 at 08 37 30](https://github.com/entur/tavla/assets/64562118/4e246d2a-9138-4bca-bcbc-7ccc13ffba6a)
![Screenshot 2023-10-30 at 08 37 43](https://github.com/entur/tavla/assets/64562118/a6a9480b-5926-4b28-ae77-b1f919fc33f7)
![Screenshot 2023-10-30 at 08 38 00](https://github.com/entur/tavla/assets/64562118/ad901e4d-702a-4fe4-9be9-7756af8f7cf4)

2023-10-30 14:09 UTC, lindtvedtsebastian requested changes

2023-10-30 14:09 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/Boards/index.tsx
> +        console.log('selectedOrganization', selectedOrganization)
console.log

2023-10-30 14:09 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/Boards/index.tsx
> +    }, [selectedOrganization, router])
Kunne vi gjort dette direkte inni onChange'en til dropdownen?

2023-10-30 14:09 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/Boards/utils/index.ts
> +export function useDropdownItems(organizations: TOrganization[]) {
Det ser ut som dette er en hook, da skal den ikke ligge i en utils fil

2023-10-30 14:09 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/Boards/utils/index.ts
> +export function useDropdownItems(organizations: TOrganization[]) {
Syntes vi kan gi den et litt mindre generisk navn også

2023-10-30 14:09 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/utils/firebase.ts
> +export async function getBoardsWithOrganization(oid: TOrganizationID) {
Syntes vi kan kalle denne `getBoardsForOrganization`

2023-10-30 15:55 UTC, fredrbus approved these changes
Synes dette ble nice 🥇

2023-10-30 15:55 UTC, fredrbus commented on next-tavla/pages/boards/[id].tsx
> +            <AdminHeader loggedIn={loggedIn} />
Om siden rendres vil vel `loggedIn` alltid være `true`, så vi kan droppe å sende inn `loggedIn` som prop og heller skrive `<AdminHeader loggedIn />`

2023-10-30 15:55 UTC, fredrbus commented on next-tavla/pages/boards/index.tsx
>              <AdminHeader loggedIn={loggedIn} />
Samme som over, ser at det er jeg som skrev den for noen uker siden men grei å ta i samme slengen 😂

2023-10-30 15:55 UTC, fredrbus commented on next-tavla/src/Admin/scenarios/Boards/hooks/useOrganizationsDropdown.ts
> +                label: org.name + ' sine tavler',
Synes kanskje det ble overflødig med "sine tavler" på alle organisasjonene i dropdown-menyen

2023-10-31 04:59 UTC, lindtvedtsebastian requested changes

2023-10-31 04:59 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/Boards/hooks/useOrganizationsDropdown.ts
> +        )
Tanken er fin, men syntes dette ble litt langt og rotete

2023-10-31 04:59 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/Boards/index.tsx
> +                            }}
Dette kan skrives om til en funksjon som eksporteres fra hooken.

Er det nødvendig å sette state når man redirecter/pusher?

2023-11-06 06:49 UTC, lindtvedtsebastian requested changes

2023-11-06 06:49 UTC, lindtvedtsebastian commented on next-tavla/pages/boards/[id].tsx
> +                        key={router.asPath}
Jeg har lyst til å undersøke hvorfor vi må ha med denne

2023-11-06 06:49 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/Boards/index.tsx
> +                        />
Jeg syntes vi burde skrive om denne til sin egen komponent

2023-11-06 13:09 UTC, natashatikhonova commented
<img width="1728" alt="image" src="https://github.com/entur/tavla/assets/64562118/abb3767e-30be-4091-9fcc-cd085bfe2a76">

2023-11-08 07:42 UTC, lindtvedtsebastian approved these changes

2023-11-08 07:49 UTC, merged