feat(travel tag): custom travel tag
entur/tavla pull request #1300
Opened 2023-11-06 18:21 UTC by fredrbus

### Description

Adds a custom travel tag with icon for transport method and line number.
Can either show transport method, line number, or both.

Determines width of the line number so it matches the widest in the column.

### Demo

https://github.com/entur/tavla/assets/61384979/95b877ee-73ad-4c5b-82ba-8c8b4929c31b

2023-11-08 07:44 UTC, lindtvedtsebastian requested changes
Er det en spesiell grunn til at vi måtte bytte ut kolonnenavnet til `publicCode`? Nå blir jo alle tavlene som tidligere har brukt `line` ødelagt. Her må det enten byttes tilbake eller skrives en converter.

2023-11-08 07:55 UTC, fredrbus commented
> Er det en spesiell grunn til at vi måtte bytte ut kolonnenavnet til `publicCode`? Nå blir jo alle tavlene som tidligere har brukt `line` ødelagt. Her må det enten byttes tilbake eller skrives en converter.

Byttet da `line` ikke gir mening i iht. dataen vi henter fra API'et. F.eks. setter man da verdier som `line={line.publicCode}`, som jeg får litt fnatt av 😬 

Kan godt skrive en converter, men trengs det når det enda ikke er i prod? Litt av poenget med beta er vel at vi ikke garanterer for visningen.

2023-11-08 09:26 UTC, lindtvedtsebastian requested changes

2023-11-08 09:26 UTC, lindtvedtsebastian commented on next-tavla/src/Shared/components/TransportIcon/index.tsx
> +    inTravelTag,
Kunne vi vurdert å bytte ut `inTravelTag` med en valgfri farge istedenfor? Kunne kanskje blitt enda mer anvendbar

2023-11-09 10:59 UTC, lindtvedtsebastian approved these changes

2023-11-09 11:08 UTC, oyvindgrutle approved these changes

2023-11-09 11:12 UTC, merged