feat(create): modal step to assign new board to organization
entur/tavla pull request #1304
Opened 2023-11-07 12:14 UTC by natashatikhonova

### Description: 
- new step in the creating board modal
- new api end point for getting all user's organizations (showing in dropdon in the modal)
-  update create board (post) request so it either creates a boared for user or for organization
- if no organization is chosen, the board will be saved as user's private board

### Image:
<img width="1326" alt="image" src="https://github.com/entur/tavla/assets/64562118/171f8676-b6da-41f4-a291-1a552fefd26b">

2023-11-07 13:24 UTC, oyvindgrutle approved these changes

2023-11-07 13:25 UTC, oyvindgrutle commented
Burde kanskje gjøre modalen høyere slik at dropdownen ikke blir gjemt hvis du er medlem av mange organisasjoner.

2023-11-07 15:03 UTC, fredrbus requested changes

2023-11-08 09:53 UTC, fredrbus approved these changes

2023-11-08 09:53 UTC, fredrbus commented on next-tavla/src/Admin/scenarios/CreateBoard/components/AddToOrganization.tsx
> +                din private bruker. Det er kun du som kan administrere tavla som
Presisere med `Da er det kun du som kan administrere...` kanskje?

2023-11-08 12:11 UTC, lindtvedtsebastian approved these changes

2023-11-08 12:16 UTC, merged