styling(create): more consistent placement and size on buttons
entur/tavla pull request #1305
Opened 2023-11-08 10:59 UTC by oyvindgrutle

More consistency regarding sizing and placement of buttons in the modal.

2023-11-08 11:06 UTC, oyvindgrutle commented
![image (1)](https://github.com/entur/tavla/assets/32832996/724292cd-4633-47e0-b3c1-f0660d1dc60a)
![image (2)](https://github.com/entur/tavla/assets/32832996/066f44cd-f581-4b1c-b26e-04ec4b3af4bf)

2023-11-08 12:12 UTC, lindtvedtsebastian requested changes

2023-11-08 12:12 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/CreateBoard/components/AddStops.tsx
> +                )}
Syntes dette kan være sin egen komponent, da kan vi returne tidlig hvis length === 0

2023-11-09 08:40 UTC, lindtvedtsebastian requested changes

2023-11-09 08:40 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/CreateBoard/components/StopPlaceList.tsx
> +}
Her er det unødvendig nesting

2023-11-09 08:41 UTC, lindtvedtsebastian approved these changes

2023-11-09 09:09 UTC, fredrbus approved these changes

2023-11-09 10:29 UTC, merged