feat(edit): global preview
entur/tavla pull request #1313
Opened 2023-11-13 13:00 UTC by natashatikhonova

### Description:
- removed preview for each tile
- show preview for the entire board (exapandable)
- update styling of edit page
### Images:
<img width="1689" alt="image" src="https://github.com/entur/tavla/assets/64562118/fb020957-7872-47c3-abdb-cb7384aa75ad">
<img width="1671" alt="image" src="https://github.com/entur/tavla/assets/64562118/acff2e89-0d4b-4670-a956-522a7f262da7">
<img width="1659" alt="image" src="https://github.com/entur/tavla/assets/64562118/453e7e46-21e0-4b8f-9656-a51345dd2010">

2023-11-13 13:52 UTC, oyvindgrutle approved these changes
LGTM

2023-11-13 14:40 UTC, lindtvedtsebastian requested changes

2023-11-13 14:40 UTC, lindtvedtsebastian commented on next-tavla/src/Board/scenarios/QuayTile/index.tsx
> +}: TQuayTile & { preview?: boolean }) {
Denne brukes vel ikke til noe?

2023-11-13 14:40 UTC, lindtvedtsebastian commented on next-tavla/src/Board/scenarios/StopPlaceTile/index.tsx
> +}: TStopPlaceTile & { preview?: boolean }) {
Denne brukes vel heller ikke til noe?

2023-11-13 14:40 UTC, lindtvedtsebastian commented on next-tavla/src/Board/scenarios/Board/index.tsx
> +function Board({ board, preview }: { board: TBoard; preview?: boolean }) {
tror ikke vi trenger `preview` proppen

2023-11-13 14:40 UTC, lindtvedtsebastian commented on next-tavla/src/Board/scenarios/Board/index.tsx
> +            return <QuayTile {...tileSpec} preview={preview} />
preview prop

2023-11-14 07:36 UTC, lindtvedtsebastian approved these changes

2023-11-14 07:55 UTC, merged