feat(organization): show organization name on edit page
entur/tavla pull request #1316
Opened 2023-11-13 14:15 UTC by oyvindgrutle

<img width="1692" alt="image" src="https://github.com/entur/tavla/assets/32832996/cdd1557b-7c77-4e34-bc76-88c63c877519">

2023-11-13 14:28 UTC, lindtvedtsebastian requested changes

2023-11-13 14:28 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/Organization/components/OrganizationTitle/index.tsx
Jeg har laget vår egen Contrast komponent. Se hvordan jeg gjorde det i `<UploadLogo/>`

2023-11-14 07:36 UTC, lindtvedtsebastian requested changes

2023-11-14 07:36 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/Organization/components/OrganizationTitle/index.tsx
Når vi har vår egen Contrast trenger vi ikke denne filen her, du kan bruke `Contrast` direkte inn i organizations (Contrast har en "use client" direktiv øverst, som gjør at alle children som blir plassert inni blir rendret på klienten)

2023-11-14 07:36 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/Organization/index.tsx
> +            <OrganizationTitle name={organization.name} />
Du kan altså legge den inn direkte her:

```tsx
<Contrast>
    <Heading1>...</Heading1>
<Contrast/>
```

2023-11-14 07:47 UTC, lindtvedtsebastian approved these changes
Nå snakker vi. Få det inn

2023-11-14 07:48 UTC, oyvindgrutle commented
> Nå snakker vi. Få det inn

Få det merga

2023-11-14 08:53 UTC, fredrbus approved these changes

2023-11-14 08:53 UTC, merged