feat(create): update create modal
entur/tavla pull request #1320
Opened 2023-11-14 13:22 UTC by natashatikhonova

### Description:
- merged organization and name page into one first page
- updated text
- all inputs/dropdowns have now the same width

### Images:
![image](https://github.com/entur/tavla/assets/64562118/cef75571-78cc-47dd-8d3b-0337e5ccbcbd)
![image](https://github.com/entur/tavla/assets/64562118/fedc7875-e7af-4276-be4a-2ad02b73d28e)

2023-11-14 13:26 UTC, lindtvedtsebastian requested changes

2023-11-14 13:26 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/types/createBoard.ts
> +export type TCreatePage = 'name&organization' | 'addStops'
Trenger vi denne typen nå? Det er vel kun en mulig side igjen

2023-11-14 13:26 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/CreateBoard/index.tsx
> +            return <AddStops popPage={popPage} board={board} />
Vi trenger kanskje bare sjekke om lastPage er noe i det hele tatt? (Altså ikke en switch)

2023-11-14 14:45 UTC, oyvindgrutle approved these changes

2023-11-15 07:39 UTC, lindtvedtsebastian approved these changes

2023-11-15 07:51 UTC, merged