fix(accessibility): tags, filter and choose columns
entur/tavla pull request #1339
Opened 2023-11-21 12:20 UTC by natashatikhonova

### Description:
- tags inside boards table will now be read like this: "list with 2 elements". "merkelapp: oslo sentrum, item 1 of 2",....
- notification badge in filter button: says how many tags are selected for filter
- choose columns: changed to contain text

2023-11-21 12:22 UTC, fredrbus approved these changes

2023-11-27 07:51 UTC, lindtvedtsebastian requested changes

2023-11-27 07:51 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/scenarios/Boards/components/FilterButton/index.tsx
Her skulle vi vel bruke vår egen komponent?

2023-11-27 07:55 UTC, lindtvedtsebastian approved these changes

2023-11-27 07:56 UTC, merged