feat(app router): migrated board
entur/tavla pull request #1350
Opened 2023-11-28 09:07 UTC by fredrbus

#### Note:
Returning 404-metadata from page.tsx since it is [not yet supported](https://github.com/vercel/next.js/issues/45620) in `not-found.tsx`

2023-11-28 09:27 UTC, oyvindgrutle approved these changes

2023-11-30 06:06 UTC, lindtvedtsebastian commented on next-tavla/app/(board)/[id]/page.tsx
> +    if (!board) return notFound()
Vi har ikke noe `notFound` side som håndterer dette?

https://nextjs.org/docs/app/api-reference/file-conventions/not-found

2023-12-01 07:23 UTC, lindtvedtsebastian requested changes

2023-12-01 07:23 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/utils/firebase.ts
> +    return { id: board.id, ...board } as TBoard
Id er ikke data som lagres i firestore, id vil ikke finnes her (det er derfor vi ikke bruker `.data()` før vi returnerer

2023-12-01 07:23 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/utils/firebase.ts
> +    return { id: oid, ...organization } as TOrganization
Samme som over

2023-12-01 07:45 UTC, fredrbus commented on next-tavla/src/Admin/utils/firebase.ts
> +    return { id: oid, ...organization } as TOrganization
Nei, `oid` blir sendt inn som funksjonsparameter

2023-12-01 07:53 UTC, lindtvedtsebastian approved these changes

2023-12-01 07:55 UTC, merged