feat(organization): delete organization
entur/tavla pull request #1354
Opened 2023-12-01 12:36 UTC by oyvindgrutle

![image](https://github.com/entur/tavla/assets/32832996/602096bf-d5bd-4838-ba1b-7f7e7c6bf197)

2023-12-12 10:44 UTC, lindtvedtsebastian requested changes

2023-12-12 10:44 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/utils/firebase.ts
> +        })
Dette bruker vi ikke lenger

2023-12-12 10:44 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/utils/firebase.ts
> +    }
Dette bruker vi ikke lenger

2023-12-12 10:44 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/utils.ts
> +    | 'organization_name'
Denne kan være mer generell, f.eks. bare `name`

2023-12-12 10:44 UTC, lindtvedtsebastian commented on next-tavla/src/Admin/utils/firebase.ts
> +    }
throw en string istedenfor

2023-12-12 10:44 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/components/Delete/index.tsx
> +    const modalIsOpen = params?.has('delete') ?? false
Vi har en egen hook for dette

2023-12-12 11:47 UTC, lindtvedtsebastian requested changes

2023-12-12 11:47 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/components/Delete/index.tsx
> +                    <FormError {...getFormFeedbackForField('name', state)} />
Denne kan du legge rett inn i navn feltet

2023-12-13 07:29 UTC, lindtvedtsebastian requested changes

2023-12-13 07:29 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/components/Delete/index.tsx
> +                <LeadParagraph>{`Er du sikker på at du vil slette organisasjonen "${organization.name}"?`}</LeadParagraph>
Hvorfor wrappes hele denne i curly braces?

```tsx
<LeadParagraph>Er du sikker på at du vil slette organisasjonen {organization.name}</LeadParagraph>
```

2023-12-13 07:29 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/components/Delete/actions.ts
> +    redirect('/organizations')
Her må du revalidere path

2023-12-13 07:29 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/utils.ts
> +                feedback: 'Organisasjonsnavnet stemmer ikke.',
Navnet på organisasjonen stemmer ikke.

2023-12-13 07:40 UTC, oyvindgrutle commented on next-tavla/app/(admin)/components/Delete/index.tsx
> +                <LeadParagraph>{`Er du sikker på at du vil slette organisasjonen "${organization.name}"?`}</LeadParagraph>
ESLint klager på qoutes hvis det ikke er wrappet.

2023-12-14 08:13 UTC, lindtvedtsebastian requested changes

2023-12-14 13:17 UTC, lindtvedtsebastian approved these changes

2023-12-14 13:17 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/components/Delete/index.tsx
> +
Denne tomme linjen kan fjernes

2023-12-14 13:21 UTC, merged