chore(app router): migrate boards
entur/tavla pull request #1367
Opened 2023-12-14 11:35 UTC by natashatikhonova

2023-12-15 10:48 UTC, oyvindgrutle requested changes

2023-12-15 10:48 UTC, oyvindgrutle commented on next-tavla/app/(admin)/boards/components/TagModal/AddNewTag.tsx
Burde fjerne innholdet i tekstfeltet etter en merkelapp er lagt til.

2023-12-15 10:48 UTC, oyvindgrutle commented on next-tavla/app/(admin)/boards/components/TableRows/index.tsx
> +                )
Virker som det funker å filtrere på en tag, hvis det er flere så filtrerer den ikke riktig.

2023-12-15 10:48 UTC, oyvindgrutle commented on next-tavla/app/(admin)/boards/utils/formActions.ts
> +        const tag = data.get('tag') as string
Burde ```tag``` enten bli gjort til lower- eller uppercase slik at det ikke er mulig å legge til samme tag, bare med forskjell i store og små bokstaver?

2023-12-15 10:59 UTC, lindtvedtsebastian requested changes

2023-12-15 10:59 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/boards/components/FilterButton/index.tsx
> +                        {filterTags?.length}
Hva skjer hvis denne er undefined

2023-12-15 10:59 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/boards/components/Sort/index.tsx
> +    }, [sortParams])
Hva er grunnen for å memoisere dette? Jeg syntes ikke vi trenger det

2023-12-15 10:59 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/boards/components/Sort/index.tsx
> +            }
trenger ikke {} her

2023-12-15 10:59 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/boards/components/TableRows/index.tsx
> +                )
Dette hadde kanskje vært enklere å forstå om man hadde definert de to filterne som funksjoner litt lenger opp

2023-12-15 10:59 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/boards/components/TagModal/AddNewTag.tsx
> +                />
Kan det oppstå feil her? Hva hvis merkelappen allerede eksisterer?

2023-12-15 10:59 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/boards/components/ToggleBoardsColumns/index.tsx
> +        }
trenger ikke {}

2023-12-15 10:59 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/boards/hooks/useSortBoardFunction.ts
> +    }, [sortParams])
samme som memo tidligere

2023-12-15 10:59 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/boards/utils/formActions.ts
> +            return getFormFeedbackForError(e)
burde returne getFormFeedbackForError('general') hvis ikke denne if'en er true

2023-12-15 10:59 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/boards/utils/formActions.ts
> +            return getFormFeedbackForError(e)
burde returne getFormFeedbackForError('general') hvis ikke denne if'en er true

2023-12-15 10:59 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/boards/utils/formActions.ts
> +            return getFormFeedbackForError(e)
burde returne getFormFeedbackForError('general') hvis ikke denne if'en er true

2023-12-15 10:59 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/boards/utils/updateTags.ts
> +    if (!user) redirect('/')
Denne redirecten vil ikke fungere siden du kaller fetchTags inni en trycatch blokk. Returner `operation-not-allowed` istedenfor

2023-12-15 10:59 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/organizations/components/CreateOrganization.tsx
Burde vi bruke en annen hook her? Da slipper vi å definere onDismiss manuelt

2023-12-15 10:59 UTC, lindtvedtsebastian commented on next-tavla/app/layout.tsx
> +            <body className="eds-contrast">{children}</body>
Hvorfor er diven fjernet? eds-contrast må ligge på den

2023-12-20 10:50 UTC, lindtvedtsebastian requested changes

2023-12-20 10:50 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/boards/[[...id]]/page.tsx
> +        : undefined
Denne funksjonen kan kanskje ta inn en `string?` og returnere undefined hvis id ikke finnes?

2023-12-20 10:50 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/boards/[[...id]]/page.tsx
> +    }
Dette trenger vel ikke være en funksjon? Kan skrives om til en variabel

2023-12-20 10:50 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/boards/components/Sort/index.tsx
> +    const sortType = sortParams?.[1] as TSort
her kan du vel bruke `sort.column` og `sort.type`?

2023-12-20 10:50 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/boards/components/TagModal/AddNewTag.tsx
> +    }
Hva er poenget med denne funksjonen? Kunne du ikke brukt action direkte i form taggen? (fjerne onSubmit og bytte ut med action)?

2023-12-20 10:50 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/boards/utils/updateTags.ts
> +    return (board.data()?.meta?.tags as TTag[]) ?? []
her kan vi godt ha litt mer whitespace

2023-12-20 10:50 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/utils.ts
> +                feedback: 'Denne taggen finnes allerede',
merkelapp kanskje?

2023-12-21 10:26 UTC, lindtvedtsebastian approved these changes

2023-12-21 10:28 UTC, merged