feat(landing): migrate landing page to app router
entur/tavla pull request #1380
Opened 2024-01-31 09:40 UTC by oyvindgrutle

# Migrate landing page to app 

![image](https://github.com/entur/tavla/assets/32832996/a34064ef-0ae2-430c-9b58-732f1c9d355f)

2024-01-31 11:02 UTC, purusott commented on next-tavla/src/Shared/styles/spacing.css
>  .w-100 {
w-120 her, siden width blir satt til 120%, eller? har ikke så mye å si for min del, men bare lurer 😅

2024-01-31 11:22 UTC, purusott approved these changes
kjempejobb 🎉 🥇 looking good 😎

2024-01-31 11:22 UTC, purusott commented on next-tavla/app/(admin)/admin.module.css
> +
Ser at de 4 klassene brukes i `page.tsx` et nivå over. Kan man ha disse i en egen fil (f.eks. `styles.module.css`) og lagt den på samme nivå som `page.tsx` filen?  💭 Vet ikke om det blir rotete eller hva som er best, tanker? 🤔

2024-01-31 11:22 UTC, purusott commented on next-tavla/app/(admin)/components/Footer/index.tsx
> +            <div className={classes.footer}>
kunne man brukt `<footer> </footer>` fremfor `<div>` et sted her, mtp UU ? 👀

2024-02-13 12:46 UTC, oyvindgrutle commented
## Create board modal
![Screenshot 2024-02-13 at 13-45-02 Forside Entur Tavla](https://github.com/entur/tavla/assets/32832996/011a2e3e-fddd-4618-8f8d-de498586341d)

## Active links in navigation
![Screenshot 2024-02-13 at 13-45-10 Organisasjoner Entur Tavla](https://github.com/entur/tavla/assets/32832996/daba3388-4652-4e14-ba71-b55bdb47803e)

2024-02-14 09:31 UTC, purusott approved these changes
bra jobba 🔥 🌟

2024-02-19 13:12 UTC, lindtvedtsebastian requested changes

2024-02-19 13:12 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/components/Footer/styles.module.css
> +}
Hvorfor ikke bruke hjelpeklasser?

2024-02-19 13:12 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/components/Footer/styles.module.css
> +}
Hjelpeklasser?

2024-02-19 13:12 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/components/Footer/styles.module.css
> +    align-content: center;
Denne funker kun hvis det er inni en flex eller grid

2024-02-19 13:12 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/admin.module.css
> +}
hjelpeklasser

2024-02-19 13:12 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/admin.module.css
> +}
hjelpeklasser

2024-02-19 13:12 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/admin.module.css
> +    width: 100%;
hjelpeklasser

2024-02-19 13:12 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/admin.module.css
> +    width: 100%;
hjelpeklasser

2024-02-19 13:12 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/admin.module.css
> +}
hjelpeklasse

2024-02-19 13:12 UTC, lindtvedtsebastian commented on next-tavla/src/Shared/styles/placement.css
> +}
vi trenger ikke enda en flex klasse, vi har flexRow og flexColumn

2024-02-19 13:12 UTC, lindtvedtsebastian commented on next-tavla/src/Shared/styles/misc.css
> +}
Brukes disse?

2024-02-19 13:12 UTC, lindtvedtsebastian commented on next-tavla/src/Shared/styles/text.css
> +}
Hva brukes denne til?

2024-02-20 05:47 UTC, oyvindgrutle commented on next-tavla/app/(admin)/components/CreateBoard/styles.module.css
> +    border: 1px solid var(--colors-brand-blue);
Hva tenker du  på?

2024-02-20 06:02 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/components/CreateBoard/styles.module.css
> +    border: 1px solid var(--colors-brand-blue);
`--colors-brand-blue` er en variabel fra designsystemet, vi har egne variabler som skiller mellom dark og light mode, se default.css og dark.css

2024-02-20 07:44 UTC, lindtvedtsebastian approved these changes

2024-02-20 07:45 UTC, merged