feat(organization): edit counties
entur/tavla pull request #1397
Opened 2024-02-20 12:05 UTC by purusott

When an organization is created, the user can update counties in the edit-organizations page.

This is solved by creating a separate file `countiesSelect.tsx` which contains checkboxes rendered by the `useCountiesSearch()`-hook wrapped in a `<form> </form>`.  

-On form submit, the chosen checkboxes will be stored in firebase connected to its _organizationID_ by updating the organization collection. 
-The `useCountiesSearch()`-hook now takes in _organizationID_ as a (optional) parameter to retrieve counties  selected by a specific organization. This is used to pre-select counties when users want to create a board for their organization (see picture below).

How it looks for now:
<img width="1016" alt="image" src="https://github.com/entur/tavla/assets/74315929/46d67242-a508-4952-bfb0-9c08e6cab080">
When the user wants to create a board, the chosen counties will be automatically selected in step 2, as shown below:
<img width="529" alt="image" src="https://github.com/entur/tavla/assets/74315929/27bb60f6-2c0e-4193-a2a4-c1058b4eae9f">

2024-02-20 12:19 UTC, oyvindgrutle approved these changes

2024-02-21 12:49 UTC, lindtvedtsebastian requested changes

2024-02-21 12:49 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/organizations/[id]/page.tsx
> +                </div>
Jeg tenker at Heading og Paragraph kan flyttes inn i CountiesSelect

2024-02-21 12:49 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/organizations/components/MemberAdministration/CountiesSelect/index.tsx
> +        <>
Dette fragmentet er vel ikke nødvendig

2024-02-21 12:49 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/organizations/components/MemberAdministration/CountiesSelect/index.tsx
> +                    className={`flexColumn flexWrap ${styles.countiesSelectContainer}`}
Når vi uansett har en klasse kan vi like gjerne legge inn de flex egenskapene i den klassen

2024-02-21 12:49 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/organizations/components/MemberAdministration/styles.module.css
> +    height: 12.5rem;
Bruk grid og grid flow istedenfor dette

2024-02-21 12:49 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/organizations/components/MemberAdministration/styles.module.css
> +.countiesSelectContainer {
Denne klassen kan du legge inn i en fil som ligger inni CountiesSelect mappen

2024-02-23 07:04 UTC, lindtvedtsebastian requested changes

2024-02-23 07:46 UTC, lindtvedtsebastian approved these changes

2024-02-23 07:48 UTC, merged