feat(board): show walking distance
entur/tavla pull request #1444
Opened 2024-03-21 10:04 UTC by oyvindgrutle

# Walking distance
If an address is set on the board, show walking duration from address to stop. Walking duration is calculated using Enturs [Journer Planner](https://developer.entur.org/pages-journeyplanner-journeyplanner).

![Screenshot 2024-03-21 at 11-03-15 Rådhusgata Entur Tavla](https://github.com/entur/tavla/assets/32832996/9b2725ee-7963-4c89-a777-db73d1960f81)
![Screenshot 2024-03-21 at 11-04-02 Rådhusgata Entur Tavla](https://github.com/entur/tavla/assets/32832996/c7613f6a-2c58-445c-bf5f-df6d65f4a7f5)
![Screenshot 2024-03-21 at 10-59-26 Entur Tavla](https://github.com/entur/tavla/assets/32832996/f1c656a7-a071-4e3f-8bb9-1929163e995c)

2024-03-22 06:29 UTC, lindtvedtsebastian requested changes

2024-03-22 06:29 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/fetch.ts
Denne filen er vel i utgangspunktet helt lik den andre fetcheren vår? Kunne vi vurdert å bare flytte hooken ut av den andre filen? Tror kanskje det skal være tilstrekkelig for å få filen til å kjøre

2024-03-22 06:29 UTC, lindtvedtsebastian commented on next-tavla/src/Shared/hooks/useWalkingDistance.ts
Denne hooken kan vel slettes 👴🏻

2024-03-22 06:29 UTC, lindtvedtsebastian commented on next-tavla/src/Shared/graphql/index.ts
Du kan bytte ut parameteret til å være placeId istedenfor stopPlaceId

2024-03-22 06:29 UTC, lindtvedtsebastian commented on next-tavla/src/Board/scenarios/Table/components/TableHeader/styles.module.css
>  }
Hele denne klassen kan vel replikeres med hjelpeklassene våre. Du kan eventuelt lage hjelpeklassene for min-height

2024-03-22 06:29 UTC, lindtvedtsebastian commented on next-tavla/src/Board/scenarios/Table/components/TableHeader/styles.module.css
> +}
Jeg lurer egentlig litt på om vi burde lage utils klasser for farger også. Du kan la denne være foreløpig

2024-03-22 06:29 UTC, lindtvedtsebastian commented on next-tavla/src/Board/scenarios/Table/components/TableHeader/index.tsx
> +            )}
Syntes dette kan være en egen komponent

2024-03-25 09:28 UTC, lindtvedtsebastian requested changes

2024-03-25 09:28 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/components/TileSelector/utils.ts
> +    if (!location) return
burde det ikke være en error her også? kunne kanskje kjørt `if (!placeId || !location)`

2024-03-25 09:28 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/components/TileSelector/utils.ts
> +    }).then((res) => res.trip.tripPatterns[0]?.duration)
Vil ikke denne returne helt andre typer erroren en form feedback? Hvordan skal dette funke

2024-03-25 09:28 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/edit/[id]/components/MetaSettings/actions.ts
> +    const tempBoard = board
hva brukes tempBoard til

2024-03-25 09:28 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/edit/[id]/components/MetaSettings/actions.ts
> +    await boardRef.update({
Funker dette? Jeg kan ikke se hva resultatet av denne mapen brukes til. Den lagres ikke i noe variabel eller lignenede?

2024-03-25 09:28 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/edit/[id]/components/TileCard/actions.ts
> +    }
dette kun godt vært en hjelpefunksjon

2024-03-25 09:41 UTC, oyvindgrutle commented on next-tavla/app/(admin)/components/TileSelector/utils.ts
> +    if (!location) return
Hvis det ikke er lagt inn noe addresse på tavla vil det da bli returnert en error

2024-03-25 10:02 UTC, oyvindgrutle commented on next-tavla/app/(admin)/edit/[id]/components/MetaSettings/actions.ts
> +    const tempBoard = board
Trengs kanskje ikke. Tanken var at det ikke var helt heldig å endre på board-objektet mens det ble iterert over

2024-03-25 15:23 UTC, lindtvedtsebastian requested changes

2024-03-25 15:23 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/components/TileSelector/utils.ts
> +    }).then((res) => res.trip.tripPatterns[0]?.duration)
Her burde vi enten bruke await eller .then
```ts
const res = await fetchQuery(...)
return res.trip.tripPatterns[0]?.duration
```
eller 
```ts
return fetchQuery(...).then((res) => ...)
```

2024-03-25 15:23 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/edit/[id]/components/MetaSettings/actions.ts
> +            }
hvis getWalkingDistance alltid returner et tall eller undefined kan vi gjøre denne snutten litt enklere

2024-03-25 15:23 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/edit/[id]/components/TileCard/actions.ts
> +    return
denne returnen gjør ingenting

2024-03-25 15:23 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/edit/[id]/components/TileCard/actions.ts
> +        }
Hvis getWalkingDistance blir simplifisert kan denne funksjonen også simplifiseres litt

```ts
async function getWalkingDistanceTile(tile: TTile, location: TLocation) {
    return {
        ...tile,
        walkingDistance: {
            ...tile.walkingDistance,
            distance: await getWalkingDistance(tile.placeId, location),
        },
    }
}

```

2024-03-25 15:23 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/edit/[id]/components/TileCard/index.tsx
> +                                walkingDistance: { visible: distance === 'on' },
Dette vil eventuelt slette eksisterende `distance`, men det er kanskje meningen

2024-03-26 10:22 UTC, oyvindgrutle commented on next-tavla/app/(admin)/edit/[id]/components/MetaSettings/actions.ts
> +    console.log('tiles', tiles)
Skal fjerne denne

2024-04-02 09:51 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/components/TileSelector/utils.ts
> +    if (!location) return undefined
Hvis vi kun skal regne ut dette når man oppdaterer/setter location vil vel !location også være en form error

2024-04-02 09:51 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/components/TileSelector/utils.ts
> +        return undefined
Burde kanskje returne formError her også

2024-04-02 09:51 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/edit/[id]/components/MetaSettings/actions.ts
> +            tiles: await getUpdatedTiles(board, location),
denne kan godt hete noe mer spesifikt relatert til lokasjon

2024-04-02 09:51 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/utils/time.ts
> +    const HOUR = 60 * MINUTE
Disse kan defineres utenfor scopet til funksjonen, nå vil de alltid initialiseres

2024-04-02 09:51 UTC, lindtvedtsebastian commented on next-tavla/src/Board/scenarios/Table/components/TableHeader/index.tsx
> +        <div className="flexRow justifyBetween alignCenter minh-2">
Hva er fordelen med minh-2 her vs vanlig height

2024-04-02 10:08 UTC, oyvindgrutle commented on next-tavla/app/(admin)/components/TileSelector/utils.ts
> +    if (!location) return undefined
Det må også regnes ut når det blir lagt til en ny tile.

2024-04-02 10:23 UTC, oyvindgrutle commented on next-tavla/src/Board/scenarios/Table/components/TableHeader/index.tsx
> +        <div className="flexRow justifyBetween alignCenter minh-2">
Usikker, har bare skrevet om til å bruke hjelpeklasser.

2024-04-03 07:53 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/edit/[id]/components/TileCard/index.tsx
> +                                defaultChecked={tile.walkingDistance?.visible}
Her må vi kanskje ha en fallback til false

2024-04-03 10:55 UTC, lindtvedtsebastian approved these changes

2024-04-03 10:55 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/edit/[id]/components/MetaSettings/actions.ts
> +    const board = (await boardRef.get()).data() as TBoard
du kan bruke getBoard her

2024-04-03 10:55 UTC, lindtvedtsebastian commented on next-tavla/src/Board/scenarios/Table/components/WalkingDistance.tsx
> +    return null
Burde heller returne null tidlig

2024-04-03 11:05 UTC, merged