docs: update github repo description
entur/tavla pull request #1450
Opened 2024-03-26 08:25 UTC by purusott

2024-03-26 08:26 UTC, lindtvedtsebastian requested changes

2024-03-26 08:26 UTC, lindtvedtsebastian commented on README.md
> +for å komme i gang!Abonner på oppdateringer til Tavla ved å klikke på “Watch”.
Her burde det vel være et mellomrom

2024-03-26 08:26 UTC, lindtvedtsebastian commented on README.md
> --   Attribution must be given to Entur Tavla when hosting your own fork/clone, and it must be visible from the dashboard pages. A link to https://tavla.entur.no must be included.
Vi burde ha med noe av dette, spesielt det med lisenser

2024-03-26 08:28 UTC, purusott commented on README.md
> --   Attribution must be given to Entur Tavla when hosting your own fork/clone, and it must be visible from the dashboard pages. A link to https://tavla.entur.no must be included.
skal vi oversette det eller ha det som før?

2024-03-27 08:10 UTC, lindtvedtsebastian approved these changes

2024-03-27 08:15 UTC, merged