feat(create): create oranization in create board modal
entur/tavla pull request #1501
Opened 2024-04-30 12:47 UTC by purusott

### Flow

## In create board modal
- <img width="963" alt="image" src="https://github.com/entur/tavla/assets/74315929/85619b37-77bc-435d-a924-a6b554f79c04">

upon clicking "Opprett ny organisasjon", the following is displayed to user:
- <img width="978" alt="image" src="https://github.com/entur/tavla/assets/74315929/ec2539f4-9506-4813-942c-65e18b47ec2a">

After clicking "opprett", an organization will be created and then selected in the first dropdown
- <img width="985" alt="image" src="https://github.com/entur/tavla/assets/74315929/345ded64-117e-4f58-a65d-1b598b842916">

**Note**: it is not possible to delete an organization after clicking the "opprett" button

2024-05-02 11:39 UTC, emilielr commented
Høre med Hannah hvordan disse knappene skal stå? Synes det ser litt packed ut: 
![image](https://github.com/entur/tavla/assets/43408175/40b58fa2-2ea0-4eff-b5a1-83b3956f5694)

2024-05-02 11:41 UTC, emilielr commented
Det er også en del ting som forsvinner som skal være en del av [skissene](https://www.figma.com/file/NAeZmYY8ikxsGNpCw9OoDW/EnTur-Tavla?type=design&node-id=2355-73112&mode=design&t=E8ZRhLjvM4d3Fzmn-0), f. eks skal headingen fortsette å være der selv om man trykker opprett ny org: 

![image](https://github.com/entur/tavla/assets/43408175/a9cddab3-179f-4339-94fa-ca0fde8af350)

2024-05-02 12:34 UTC, emilielr commented on next-tavla/app/(admin)/components/CreateBoard/index.tsx
> +            <div>
Trenger vi `div` her?

2024-05-02 12:34 UTC, emilielr commented on next-tavla/app/(admin)/components/CreateBoard/index.tsx
> +                        <Label className="weight500">
Bruke tailwind her i stedet?

2024-05-02 12:34 UTC, emilielr commented on next-tavla/app/(admin)/components/CreateBoard/index.tsx
> +                                className="ml-6"
Dette kan også være personlig preferanse, men jeg er mer fan av å unngå å sette margins osv på spesifikke komponenter når man skal distansere de fra noe annet. Da vil det se rart ut om de plutselig blir liggende på hver sin "rad", slik som dette: 
![image](https://github.com/entur/tavla/assets/43408175/3a6a8f22-5e9d-47cd-b1d1-afe695dbd00a)

Et forslag kan være at man legger på `flex gap-6` på den diven som wrapper disse to knappene (linje 226) - da kan ma gjøre den mobilvennlig med det samme 😄

2024-05-02 12:34 UTC, emilielr commented on next-tavla/app/(admin)/components/CreateBoard/index.tsx
> +                                        .includes(orgName.current.value)
Kan vi skrive denne litt enklere ved å bruke `some()`-funksjonen?

2024-05-03 04:40 UTC, purusott commented
> Høre med Hannah hvordan disse knappene skal stå? Synes det ser litt packed ut
Viste hun en demo av det og da sa hun at det så greit ut 🤔 Men skal fikse opp i de andre kommentarene og ta en runde til 👍  hjelper nok å se det flere ganger 😅

2024-05-06 12:29 UTC, lindtvedtsebastian requested changes

2024-05-06 12:29 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/components/CreateBoard/index.tsx
> +
Jeg syntes det blir litt voldsomt med booleans og nesting osv her, kan vi prøve å rydde litt opp? 🥇

2024-05-06 12:29 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/hooks/useOrganizations.ts
Jeg syntes logikken her er litt rar, er vi sikre på at dette er måten vi skal gjøre dette på?

2024-05-06 12:29 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/organizations/components/CreateOrganization/actions.ts
> +    return formError
kunne vi ikke bare returnert oid her

2024-05-07 06:09 UTC, emilielr approved these changes
🌶️

2024-05-13 12:16 UTC, closed without merging