feat(navigation): side nav on mobile decives
entur/tavla pull request #1516
Opened 2024-05-24 09:30 UTC by emilielr

After: 
![image](https://github.com/entur/tavla/assets/43408175/a1be3ba9-38ac-40af-88a1-84b32db81f13)

![image](https://github.com/entur/tavla/assets/43408175/1625dafe-fa9d-4b5a-9887-0ee523583618)

2024-05-27 06:18 UTC, lindtvedtsebastian requested changes

2024-05-27 06:18 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/components/SideNavBar.tsx
> +                        </form>
Kunne vi vurdert en action her?

```tsx
<form action={logout}>
  <SideNavigationItem
    as={Button}
    type="submit"
    style={{
      justifyContent: 'start',
      padding: '0rem 2.5rem',
    }}
  >
    Logg ut
  </SideNavigationItem>
</form>
```

2024-05-27 06:18 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/components/SideNavBar.tsx
> +                                }}
hvorfor er dette inline style?

2024-05-27 06:18 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/components/CreateBoard/index.tsx
> +function CreateBoard({ isSideNav }: { isSideNav?: boolean }) {
Kunne vi vurdert å flytte denne logikken ut av komponenten og heller sendt inn en boolean på om den er åpen eller ikke?

2024-05-27 06:39 UTC, emilielr commented on next-tavla/app/(admin)/components/SideNavBar.tsx
> +                        </form>
Logikken funket ikke 100% med å bruke action, jeg måtte få til at sideNaven ble lukket når man logget seg ut. Hvis ikke var den automatisk satt til åpen når man logget seg ut, også logget seg inn igjen

2024-05-27 07:39 UTC, purusott approved these changes

2024-05-27 07:45 UTC, emilielr commented on next-tavla/app/(admin)/components/SideNavBar.tsx
> +                                }}
borte nå:)

2024-05-29 08:34 UTC, lindtvedtsebastian approved these changes

2024-05-29 08:35 UTC, merged