feat(boards): new bords view and org. name as column
entur/tavla pull request #1532
Opened 2024-05-30 10:57 UTC by emilielr

- Komponent: https://design.entur.no/komponenter/layout-og-flater/table#sortering-av-tabell
- Laget en ny type hvor man har et `board`-object og et `organization`-objekt. Det er dette objektet som blir brukt til å sorteres på. 
- 

![image](https://github.com/entur/tavla/assets/43408175/e0881379-4226-4488-8129-43cb9f29af07)

2024-06-04 11:29 UTC, purusott commented
Jeg opprettet en _ny bruker_ og gikk inn på tavlesiden. Der får jeg opp mange tavler, selv om jeg ikke har laget noen enda. Mistenker det er tavler til de andre brukerne i db 🤔 Skjer det bare hos meg?

2024-06-04 11:59 UTC, purusott requested changes
Jeg tror det er et problem i tavlesiden hvor man kan få inn tavlene til andre brukere. Jeg opprettet en ny bruker og hadde mange tavler på min tavleside da jeg sjekket det ut lokalt  🤔 💭

2024-06-04 11:59 UTC, purusott commented on next-tavla/app/(admin)/boards/components/Column/Organization.tsx
> +        organization.name == undefined ? 'Privat' : organization.name
kunne man ha skrevet det slik:  `const orgName = organization.name ?? 'Privat'`, så blir det litt kortere 😎

2024-06-04 11:59 UTC, purusott commented on next-tavla/app/(admin)/boards/components/Column/Name.tsx
> +                {board.meta.title ?? DEFAULT_BOARD_NAME}
kan vi vurdere `board.meta?.title` (eller noe annet) i tilfelle vi har flere tavler i prod uten meta feltet 🤔

2024-06-04 11:59 UTC, purusott commented on next-tavla/app/(admin)/actions.ts
> +    const boardRef = await firestore().collection('boards').get()
Her tror jeg vi må gjøre noe mer for å kun hente boards til en spesifikk bruker. kanksje ta inn uid også filtrere boards owners på det elns 💭

2024-06-05 12:22 UTC, emilielr commented
Her har det gått fort i svingene 😅 Har fikset det nå!

2024-06-10 08:16 UTC, purusott approved these changes

2024-06-11 08:43 UTC, lindtvedtsebastian requested changes

2024-06-11 08:43 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/boards/components/BoardTable/index.tsx
> +        </Table>
Jeg får opp flere problemer i node, virker som det skjer noe greier i Table komponenten som krasjer serveren. Prøv å import den uten ssr (lazy) og se om det funker da

2024-06-11 08:43 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/boards/[[...id]]/page.tsx
Denne filen sin path burde endres, vi trenger ikke lenger organization id som param

2024-06-11 08:43 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/actions.ts
> +}
Foreslår å hente ut all informasjonen vi trenger direkte her. 

En mulig måte å gjøre dette på:

```ts
export async function getBoards(ids?: TBoardID[]) {
    if (!ids) return []
    const batches = chunk(ids, 20)
    const queries = batches.map((batch) =>
        firestore()
            .collection('boards')
            .where(firestore.FieldPath.documentId(), 'in', batch)
            .get(),
    )
    const refs = await Promise.all(queries)
    return refs
        .map((ref) =>
            ref.docs.map((doc) => ({ id: doc.id, ...doc.data() } as TBoard)),
        )
        .flat()
}

export async function getAllBoardsForUser(): Promise<
    { board: TBoard; organization?: TOrganization }[]
> {
    const user = await getUser()
    if (!user) return redirect('/')

    const privateBoardIDs = concat(user.owner ?? [], user.editor ?? [])

    const privateBoards = (await getBoards(privateBoardIDs)).map((board) => ({
        board,
    }))

    const organizations = await getOrganizationsForUser()

    const organizationsBoards = flattenDeep(
        await Promise.all(
            organizations.map(async (organization) =>
                (
                    await getBoards(organization.boards)
                ).map((board) => ({
                    board,
                    organization,
                })),
            ),
        ),
    )
    return [...organizationsBoards, ...privateBoards]
}
```

2024-06-14 06:21 UTC, closed without merging