styling(preview): show full board in preview
entur/tavla pull request #1548
Opened 2024-06-13 11:44 UTC by oyvindgrutle

![image](https://github.com/entur/tavla/assets/32832996/67ef6396-e068-4695-af72-ec41d77276e7)

2024-06-13 12:41 UTC, purusott approved these changes

2024-06-13 13:36 UTC, lindtvedtsebastian requested changes

2024-06-13 13:36 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/edit/[id]/page.tsx
> -                    <ClientBoard board={board} />
Brukes denne?

2024-06-14 05:53 UTC, lindtvedtsebastian approved these changes

2024-06-14 05:56 UTC, merged