chore(tags): tags colors
entur/tavla pull request #1578
Opened 2024-07-08 05:18 UTC by oyvindgrutle

2024-07-08 08:49 UTC, purusott approved these changes

2024-07-08 11:15 UTC, oyvindgrutle commented on next-tavla/app/(admin)/boards/utils/actions.ts
> +
Det blir sjekket i ```deteleBoard```

2024-07-09 11:30 UTC, emilielr requested changes
Nå er gamle tagger enda i lowercase her, fikse at disse også er uppercase? 

Det er også mulig å legge til en tom string som tag, få inn en sjekk på at det må være mer enn ""?

![image](https://github.com/entur/tavla/assets/43408175/e5e17bb7-7754-4481-b02d-a25a11b00316)

2024-07-09 11:42 UTC, emilielr commented
Enige om i plenum: 
- Ikke lagre tags som uppercase i firebase (heller lage en sjekk som sammenligner på uppercase)
- Heller vise uppercase i frontend (både i adminstrer merkelapper + selve tagsene + i filtreringknappen)

![image](https://github.com/entur/tavla/assets/43408175/7edf8eed-5713-4ae2-bf6d-b275e6e6fb38)

2024-07-12 12:06 UTC, emilielr commented on next-tavla/app/(admin)/boards/utils/index.ts
> +]
ta bort kommentarene?

2024-07-12 12:57 UTC, emilielr commented on next-tavla/app/(admin)/boards/utils/index.ts
> +    'lilac', // Lilac
ta bort kommentarene?

2024-07-12 12:57 UTC, emilielr commented on next-tavla/app/(admin)/utils/index.ts
> +                feedback: 'Merkelappen kan ikke være tom eller bare mellomrom.',
legge til: ...bare _bestå av_ mellomrom.

2024-07-12 12:57 UTC, emilielr commented on next-tavla/app/globals.css
> +        --data-visualization-spring: var(--colors-data-default-spring);
gjerne legg til alle disse for de andre theme vi har og så de alltid har like variabler

2024-07-12 12:57 UTC, emilielr commented on next-tavla/tailwind.config.ts
> +
kan bytte ut alle disse å bare skrive `...dataColors`

2024-07-12 12:57 UTC, emilielr commented on next-tavla/app/(admin)/boards/utils/index.ts
> +const colors = [
kan man hente disse farge-navnene fra `dataColors`-objektet, så trenger man kun å endre en plass om man vil endre farger? Noe: 

`Object.keys()..`

2024-07-12 12:57 UTC, emilielr commented on next-tavla/app/(admin)/boards/components/Column/Tags.tsx
> +                const color = `var(--data-visualization-${colorsFromHash(tag)})`
ikke helt fan av dette, men ser ikke ut som man får satt farge på noen annen måte:(

2024-07-15 11:20 UTC, emilielr approved these changes

2024-07-15 11:20 UTC, emilielr commented on next-tavla/app/(admin)/boards/utils/index.ts
> +export const colors = {
`dataColors`? 👼

2024-07-19 07:12 UTC, merged