feat(create): reduce steps in create board modal
entur/tavla pull request #1580
Opened 2024-07-08 11:50 UTC by oyvindgrutle

2024-07-09 10:51 UTC, emilielr requested changes

2024-07-09 10:51 UTC, emilielr commented on next-tavla/app/(admin)/components/CreateBoard/index.tsx
>      const [board, setBoard] = useState<TBoard>()
denne staten gjør ingenting. trengs ikke å "spreades" i `create()`-funksjonen heller siden den alltid er undefined

2024-07-12 06:24 UTC, emilielr approved these changes
🧘‍♀️ synes denne ble clean 🤌

2024-07-12 07:55 UTC, purusott approved these changes

2024-07-16 05:38 UTC, merged