feat(edit): redesign of layout
entur/tavla pull request #1601
Opened 2024-07-31 07:57 UTC by emilielr

![image](https://github.com/user-attachments/assets/3e3f0b65-d9b8-436b-be12-d8b6d2fa420a)
![image](https://github.com/user-attachments/assets/e1046dce-ed5f-465c-93c6-05f88386c0bd)

2024-08-06 05:56 UTC, lindtvedtsebastian requested changes
Jeg ser at vi overskriver designsystemet flere steder, jeg regner med at dette er fordi fargene ikke var riktig. Du kan oppdatere @entur/button, da blir alt litt penere som default

2024-08-06 05:56 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/edit/[id]/components/TileCard/index.tsx
> +                    className={`flex justify-between items-center px-6  py-4 bg-[var(--colors-blues-blue80)] w-full ${
Kunne vi ikke brukt `bg-blue80` her også?

2024-08-06 05:56 UTC, lindtvedtsebastian commented on next-tavla/app/(admin)/edit/[id]/components/TileCard/index.tsx
> +                        className="*:!border-primary"
Er det noe spesifikk grunn til at vi overskriver designsystemet her? 🤔

2024-08-07 08:15 UTC, purusott approved these changes

2024-08-07 08:43 UTC, lindtvedtsebastian approved these changes
![image](https://github.com/user-attachments/assets/96b81881-29fc-4c08-9c55-095529d7041c)

2024-08-07 08:44 UTC, merged