feat(backend): endpoint for updating single board
entur/tavla pull request #1623
Opened 2024-08-27 13:38 UTC by emilielr

2024-08-27 18:21 UTC, lindtvedtsebastian requested changes

2024-08-27 18:21 UTC, lindtvedtsebastian commented on backend/src/main.rs
> +        .publish(bid, BoardAction::Refresh { payload: payload })
```rust
BoardAction::Refresh { payload: payload }
```
kan forenkles:
```rust
BoardAction::Refresh { payload}
```

2024-08-27 18:21 UTC, lindtvedtsebastian commented on backend/src/main.rs
> +        .publish(bid, to_string(&BoardAction::Update)?) // "update"
Denne kommentaren gir minimalt med verdi

2024-08-27 18:21 UTC, lindtvedtsebastian commented on backend/src/main.rs
> +                    BoardAction::Refresh { payload } => Message::Refresh { payload: payload },
```rust
Message::Refresh { payload: payload }
```
kan forenkles:
```rust
Message::Refresh { payload}
```

2024-08-27 18:21 UTC, lindtvedtsebastian commented on backend/src/utils.rs
> +        protocol: redis::ProtocolVersion::RESP3,
Er det noe spesifikk grunn til at vi bruker denne protokollen her? Ser at det nylig ble støttet 🤔 

https://docs.rs/redis/latest/redis/#resp3-support

2024-08-28 05:23 UTC, purusott commented on backend/src/utils.rs
> +        protocol: redis::ProtocolVersion::RESP3,
compileren kastet først en error om at vi ikke har spesifisert protokoll. Vi antok bare at resp3 var "bedre" siden det er nyere, men ellers ikke noe spes grunn

2024-08-28 05:25 UTC, purusott commented
Burde vi håndtere publish på en bid som ikke er en channel, i `update_board`?

2024-08-28 08:51 UTC, lindtvedtsebastian approved these changes

2024-08-28 08:51 UTC, lindtvedtsebastian commented on backend/src/types.rs
> +        }
Jeg tror denne kan forenkles

```rust
match to_string(self) {
  Ok(s) => out.write_arg_fmt(s),
  Err(_) => out.write_arg_fmt(0_u8),
}
```

2024-08-28 13:46 UTC, merged