Add posthog to landing page
entur/tavla pull request #1630
Opened 2024-09-03 07:18 UTC by SelmaBergstrand

Posthog captures added to:

- landing page buttons
- nav bar buttons

See new graphs in posthog dashboard.

2024-09-03 09:25 UTC, emilielr requested changes

2024-09-03 09:25 UTC, emilielr commented on tavla/app/components/LandingBanner/index.tsx
Det eneste i denne komponenten som trenger å være klientkomponent er knappene. Resten er tekst og bilder, som vi kan ha som en server component 🖥️

2024-09-03 09:25 UTC, emilielr commented on tavla/app/page.tsx
>                  <div className="flex flex-col justify-center pb-10">
Her er det 3 diver på rad, trenger vi alle de eller kan noe slås sammen?

2024-09-03 10:11 UTC, SelmaBergstrand commented on tavla/app/page.tsx
> +                <LandingBanner loggedIn={loggedIn} />
Tenker du på å flytte hele definisjonen av loggedIn inn i komponenten? Komponenten må ha 'use client' for å kunne gjøre posthog, og da funker det ikke å kjøre verifySession. Så tror kanskje det må bli som det

2024-09-03 10:13 UTC, SelmaBergstrand commented on tavla/app/page.tsx
>                  <div className="flex flex-col justify-center pb-10">
Jeg og Åse prøvde og se på om en kunne fjernes men fikk det ikke til :((

2024-09-04 13:53 UTC, emilielr commented on tavla/app/page.tsx
> +                <LandingBanner loggedIn={loggedIn} />
Likte egentlig at vi hadde skilt ut i en `LandingBanner`, men det jeg tenke på var at `LandingBanner` kunne være en server komponent som kan bruke `verifySession`, også skilte man ut knappene man hadde i `LandingBanner` ut i egne klient komponenter. Da vil knappene kunne bruke posthog, og `LandingBanner` er en serverkomponent som kan bruke `verifySession`.

2024-09-04 13:54 UTC, emilielr commented on tavla/app/page.tsx
> +                <LandingBanner loggedIn={loggedIn} />
Men om man vil skille ut `LandingBanner` i en egen komponent er litt smak og behag!

2024-09-05 06:37 UTC, merged