feat(landing): add word carousel to landing page
entur/tavla pull request #1635
Opened 2024-09-04 13:22 UTC by asewilhelmsen

Added a word carousel to the landing page: 
![Screenshot 2024-09-04 at 15 22 29](https://github.com/user-attachments/assets/8248e564-aec8-4a5b-aa31-078ab65321a1)

2024-09-05 06:57 UTC, asewilhelmsen commented on tavla/app/components/WordCarousel.tsx
> +        <Heading1
Usikker på om denne bør være H1 eller noe annet. Spørre Ragnhild

2024-09-05 10:04 UTC, emilielr requested changes

2024-09-05 10:04 UTC, emilielr commented on tavla/app/components/WordCarousel.tsx
> +        <Heading1
H1 er nok greit

2024-09-05 10:10 UTC, emilielr approved these changes

2024-09-05 11:45 UTC, SelmaBergstrand approved these changes

2024-09-06 05:23 UTC, purusott approved these changes

2024-09-06 06:10 UTC, merged