Show full boards on landing page
entur/tavla pull request #1653
Opened 2024-09-18 10:01 UTC by SelmaBergstrand

Hele tavler i preview-karusellen, kan nå vise logo, klokke og flere tiles:

![Screenshot 2024-09-18 at 11 42 00](https://github.com/user-attachments/assets/ed085fcf-e054-4512-b0af-8bd19a048b14)

Mobil:

![Screenshot 2024-09-18 at 12 01 19](https://github.com/user-attachments/assets/59007233-f3ef-4e9d-9e27-81b164fa5cba)

2024-09-19 13:11 UTC, emilielr requested changes
Hmmmm, her har det skjedd noe rart. Synes også logoen var veeeldig stor? Tar gjerne en sparring på design/css om du ønsker å ikke sitte helt alene!

![image](https://github.com/user-attachments/assets/453c3137-a3ff-446f-a8b6-e32ef18fb0bc)

2024-09-19 13:11 UTC, emilielr commented on tavla/app/(admin)/edit/[id]/components/Preview/index.tsx
> +    landingPage?: boolean
Skjønner tanken med å sende inn `landingPage` her, men siden det kun er stylingen som endres så kan det kanskje være lettere om vi bare kopierer over dette i `PreviewCarousel` i stedet? Også kan vi f. eks legge `classname="rounded p-4 bg-primary border border-secondary"` inn i `globals.css` for å bli brukt begge plasser. Tar gjerne en liten snakk på denne

2024-09-23 08:33 UTC, emilielr approved these changes

2024-09-23 08:33 UTC, purusott approved these changes

2024-09-23 08:33 UTC, merged