dragndrop
entur/tavla pull request #268
Opened 2020-09-11 12:56 UTC by 3l-3m1n

whitespace-removal

chrono-view-quick-fix

fixade bredd i Chrono-view

fjerne scroll i tile

whitespace-fix

2020-09-11 14:46 UTC, draperunner commented on src/dashboards/Chrono/index.tsx
> +    const numberOfStopPlaces = stopPlacesWithDepartures
Du kan forenkle dette til
```
const numberOfStopPlaces = stopPlacesWithDepartures?.length || 0
```

2020-09-11 14:46 UTC, draperunner commented on src/dashboards/Chrono/index.tsx
> +        getFromLocalStorage(history.location.key) || {}
Denne vil hente inn frå `localStorage` kvar gong `ChronoDashboard` rendrer. Det høyrest ut som ein litt tung operasjon å gjere så ofte.

Det går kanskje an å holde `layouts` i ein `useState`, og heller initialisere denne med det som er i localStorage?

```
const [layouts, setLayouts] = useState(getFromLocalStorage(history.location.key) || {})
```

```
useEffect(() => {
  saveToLocalStorage(dashboardKey, layouts)
}, [dashboardKey, layouts])
```

```
onLayoutChange={(
                        layout: Layout[],
                        layouts: Layouts,
                    ): void => {
                        if (numberOfStopPlaces > 0) {
                            setLayouts(layouts)
                        }
                    }}

2020-09-14 11:01 UTC, 3l-3m1n commented on src/dashboards/Chrono/index.tsx
> +    const numberOfStopPlaces = stopPlacesWithDepartures
Endret!

2020-09-14 11:01 UTC, 3l-3m1n commented on src/dashboards/Chrono/index.tsx
> +        getFromLocalStorage(history.location.key) || {}
Endret!

2020-09-14 12:19 UTC, draperunner requested changes
Bra, det ser bedre ut. 

Eg trur `onLayoutChange`-funksjonen er ubrukt no og kan slettast. Det er eit par andre ESLint-feil også. `npm run eslint -- --fix` bør fikse ein del. Installer gjerne ESLint-plugin i editoren din.

2020-09-14 15:20 UTC, draperunner approved these changes

2020-09-15 07:29 UTC, merged