Fix visual expression on tab-list on mobile
entur/tavla pull request #342
Opened 2021-06-28 14:28 UTC by anneliseostby

Change min-width on tab in tab-panel on small screens, s.t all text is visable.
Make fading on the right end of tab-list on mobile screens.

Before: left, after: right
<img src="https://user-images.githubusercontent.com/67413374/123651838-19539200-d82c-11eb-8c85-8e6661687a00.png" alt="preview" width="250"/><img src="https://user-images.githubusercontent.com/67413374/123651843-1a84bf00-d82c-11eb-97e9-5b21c32ef8ca.png" alt="preview" width="250"/>

2021-06-28 14:38 UTC, Magnus-V commented on src/containers/Admin/styles.scss
> +            min-width: 10em;
Endre til rem

2021-06-28 14:42 UTC, Magnus-V requested changes
En liten endring fra em til rem, og en tommel opp fra Marlin så er det bare å kjøre på.

2021-06-29 08:17 UTC, Magnus-V approved these changes

2021-06-29 08:19 UTC, draperunner approved these changes

2021-06-29 09:09 UTC, quesara approved these changes

2021-06-29 09:11 UTC, merged